#!/usr/bin/env python3

import attr
from wrdscli.lib.base import WRDSEntity

@attr.s(auto_attribs=True)
class Fdmt(WRDSEntity):
    schema = 'comp'
    table = 'fundq'
    gvkey: str  # A Unique Global Company Key
    datadate: str  # Data Date
    popsrc: str  # Population Source
    iid: str  # Unique Issue ID
    indfmt: str  # Industry format
    datafmt: str  # Data Format
    consol: str  # Level of Consolidation
    costat: str  # Active/Inactive Status Marker
    curcdq: str = None  # ISO Currency Code
    acchgq: int = None  # ACCHGQ -- Accounting Changes - Cumulative Effect
    acchgy: int = None  # ACCHGY -- Accounting Changes - Cumulative Effect
    acctchgq: str = None  # ACCTCHGQ -- Adoption of Accounting Changes
    acctstdq: str = None  # ACCTSTDQ -- Accounting Standard
    acomincq: int = None  # ACOMINCQ -- Accumulated Other Comprehensive Income (Loss)
    acoq: int = None  # ACOQ -- Current Assets - Other - Total
    actq: int = None  # ACTQ -- Current Assets - Total
    add1: str = None  # ADD1 -- Address Line 1
    add2: str = None  # ADD2 -- Address Line 2
    add3: str = None  # ADD3 -- Address Line 3
    add4: str = None  # ADD4 -- Address Line 4
    addzip: str = None  # ADDZIP -- Postal Code
    adjex: int = None  # ADJEX -- Cumulative Adjustment Factor by Ex-Date
    adrrq: int = None  # ADRRQ -- ADR Ratio
    afudccy: int = None  # AFUDCCY -- Allowance for Funds Used During Construction (Cash Flow)
    afudciy: int = None  # AFUDCIY -- Allowance for Funds Used During Construction (Investing) (Cash Flow)
    ajexq: int = None  # AJEXQ -- Adjustment Factor (Company) - Cumulative by Ex-Date
    ajpq: int = None  # AJPQ -- Adjustment Factor (Company) - Cumulative byPay-Date
    altoq: int = None  # ALTOQ -- Other Long-term Assets
    amcy: int = None  # AMCY -- Amortization (Cash Flow)
    ancq: int = None  # ANCQ -- Non-Current Assets - Total
    anoq: int = None  # ANOQ -- Assets Netting & Other Adjustments
    aociderglq: int = None  # AOCIDERGLQ -- Accum Other Comp Inc - Derivatives Unrealized Gain/Loss
    aociotherq: int = None  # AOCIOTHERQ -- Accum Other Comp Inc - Other Adjustments
    aocipenq: int = None  # AOCIPENQ -- Accum Other Comp Inc - Min Pension Liab Adj
    aocisecglq: int = None  # AOCISECGLQ -- Accum Other Comp Inc - Unreal G/L Ret Int in Sec Assets
    aol2q: int = None  # AOL2Q -- Assets Level2 (Observable)
    aolochy: int = None  # AOLOCHY -- Assets and Liabilities - Other (Net Change)
    aoq: int = None  # AOQ -- Assets - Other - Total
    apalchy: int = None  # APALCHY -- Accounts Payable and Accrued Liabilities - Increase (Decrease)
    apdedateq: str = None  # APDEDATEQ -- Actual Period End date
    apq: int = None  # APQ -- Account Payable/Creditors - Trade
    aqaq: int = None  # AQAQ -- Acquisition/Merger After-Tax
    aqay: int = None  # AQAY -- Acquisition/Merger After-Tax
    aqcy: int = None  # AQCY -- Acquisitions
    aqdq: int = None  # AQDQ -- Acquisition/Merger Diluted EPS Effect
    aqdy: int = None  # AQDY -- Acquisition/Merger Diluted EPS Effect
    aqepsq: int = None  # AQEPSQ -- Acquisition/Merger Basic EPS Effect
    aqepsy: int = None  # AQEPSY -- Acquisition/Merger Basic EPS Effect
    aqpl1q: int = None  # AQPL1Q -- Assets Level1 (Quoted Prices)
    aqpq: int = None  # AQPQ -- Acquisition/Merger Pretax
    aqpy: int = None  # AQPY -- Acquisition/Merger Pretax
    arcedq: int = None  # ARCEDQ -- As Reported Core - Diluted EPS Effect
    arcedy: int = None  # ARCEDY -- As Reported Core - Diluted EPS Effect
    arceepsq: int = None  # ARCEEPSQ -- As Reported Core - Basic EPS Effect
    arceepsy: int = None  # ARCEEPSY -- As Reported Core - Basic EPS Effect
    arceq: int = None  # ARCEQ -- As Reported Core - After-tax
    arcey: int = None  # ARCEY -- As Reported Core - After-tax
    atq: int = None  # ATQ -- Assets - Total
    aul3q: int = None  # AUL3Q -- Assets Level3 (Unobservable)
    billexceq: int = None  # BILLEXCEQ -- Billings in Excess of Cost & Earnings
    bsprq: str = None  # BSPRQ -- Balance Sheet Presentation
    busdesc: str = None  # BUSDESC -- S&P Business Description
    capr1q: int = None  # CAPR1Q -- Risk-Adjusted Capital Ratio - Tier 1
    capr2q: int = None  # CAPR2Q -- Risk-Adjusted Capital Ratio - Tier 2
    capr3q: int = None  # CAPR3Q -- Risk-Adjusted Capital Ratio - Combined
    capsftq: int = None  # CAPSFTQ -- Capitalized Software
    capsq: int = None  # CAPSQ -- Capital Surplus/Share Premium Reserve
    capxy: int = None  # CAPXY -- Capital Expenditures
    cdvcy: int = None  # CDVCY -- Cash Dividends on Common Stock (Cash Flow)
    ceiexbillq: int = None  # CEIEXBILLQ -- Cost & Earnings in Excess of Billings
    ceqq: int = None  # CEQQ -- Common/Ordinary Equity - Total
    chechy: int = None  # CHECHY -- Cash and Cash Equivalents - Increase (Decrease)
    cheq: int = None  # CHEQ -- Cash and Short-Term Investments
    chq: int = None  # CHQ -- Cash
    cibegniq: int = None  # CIBEGNIQ -- Comp Inc - Beginning Net Income
    cibegniy: int = None  # CIBEGNIY -- Comp Inc - Beginning Net Income
    cicurrq: int = None  # CICURRQ -- Comp Inc - Currency Trans Adj
    cicurry: int = None  # CICURRY -- Comp Inc - Currency Trans Adj
    ciderglq: int = None  # CIDERGLQ -- Comp Inc - Derivative Gains/Losses
    cidergly: int = None  # CIDERGLY -- Comp Inc - Derivative Gains/Losses
    cik: str = None  # CIK Number
    cimiiq: int = None  # CIMIIQ -- Comprehensive Income - Noncontrolling Interest
    cimiiy: int = None  # CIMIIY -- Comprehensive Income - Noncontrolling Interest
    ciotherq: int = None  # CIOTHERQ -- Comp Inc - Other Adj
    ciothery: int = None  # CIOTHERY -- Comp Inc - Other Adj
    cipenq: int = None  # CIPENQ -- Comp Inc - Minimum Pension Adj
    cipeny: int = None  # CIPENY -- Comp Inc - Minimum Pension Adj
    ciq: int = None  # CIQ -- Comprehensive Income - Total
    cisecglq: int = None  # CISECGLQ -- Comp Inc - Securities Gains/Losses
    cisecgly: int = None  # CISECGLY -- Comp Inc - Securities Gains/Losses
    citotalq: int = None  # CITOTALQ -- Comprehensive Income - Parent
    citotaly: int = None  # CITOTALY -- Comprehensive Income - Parent
    city: str = None  # CITY -- City
    ciy: int = None  # CIY -- Comprehensive Income - Total
    cogsq: int = None  # COGSQ -- Cost of Goods Sold
    cogsy: int = None  # COGSY -- Cost of Goods Sold
    compstq: str = None  # COMPSTQ -- Comparability Status
    conm: str = None  # Company Name
    conml: str = None  # CONML -- Company Legal Name
    county: str = None  # COUNTY -- County Code
    csh12q: int = None  # CSH12Q -- Common Shares Used to Calculate Earnings Per Share - 12 Months Moving
    cshfd12: int = None  # CSHFD12 -- Common Shares Used to Calc Earnings Per Share - Fully Diluted - 12 Months M
    cshfdq: int = None  # CSHFDQ -- Com Shares for Diluted EPS
    cshfdy: int = None  # CSHFDY -- Com Shares for Diluted EPS
    cshiq: int = None  # CSHIQ -- Common Shares Issued
    cshopq: int = None  # CSHOPQ -- Total Shares Repurchased - Quarter
    cshoq: int = None  # CSHOQ -- Common Shares Outstanding
    cshprq: int = None  # CSHPRQ -- Common Shares Used to Calculate Earnings Per Share - Basic
    cshpry: int = None  # CSHPRY -- Common Shares Used to Calculate Earnings Per Share - Basic
    cshtrq: int = None  # CSHTRQ -- Common Shares Traded - Quarter
    cstkcvq: int = None  # CSTKCVQ -- Carrying Value
    cstkeq: int = None  # CSTKEQ -- Common Stock Equivalents - Dollar Savings
    cstkey: int = None  # CSTKEY -- Common Stock Equivalents - Dollar Savings
    cstkq: int = None  # CSTKQ -- Common/Ordinary Stock (Capital)
    curncdq: str = None  # CURNCDQ -- Native Currency Code
    currtrq: int = None  # CURRTRQ -- Currency Translation Rate
    curuscnq: int = None  # CURUSCNQ -- US Canadian Translation Rate - Interim
    cusip: str = None  # CUSIP
    datacqtr: str = None  # DATACQTR -- Calendar Data Year and Quarter
    datafqtr: str = None  # DATAFQTR -- Fiscal Data Year and Quarter
    dcomq: int = None  # DCOMQ -- Deferred Compensation
    dd1q: int = None  # DD1Q -- Long-Term Debt Due in One Year
    depcy: int = None  # DEPCY -- Depreciation and Depletion (Cash Flow)
    deracq: int = None  # DERACQ -- Derivative Assets - Current
    deraltq: int = None  # DERALTQ -- Derivative Assets Long-Term
    derhedglq: int = None  # DERHEDGLQ -- Gains/Losses on Derivatives and Hedging
    derhedgly: int = None  # DERHEDGLY -- Gains/Losses on Derivatives and Hedging
    derlcq: int = None  # DERLCQ -- Derivative Liabilities- Current
    derlltq: int = None  # DERLLTQ -- Derivative Liabilities Long-Term
    diladq: int = None  # DILADQ -- Dilution Adjustment
    dilady: int = None  # DILADY -- Dilution Adjustment
    dilavq: int = None  # DILAVQ -- Dilution Available - Excluding Extraordinary Items
    dilavy: int = None  # DILAVY -- Dilution Available - Excluding Extraordinary Items
    dlcchy: int = None  # DLCCHY -- Changes in Current Debt
    dlcq: int = None  # DLCQ -- Debt in Current Liabilities
    dldte: str = None  # DLDTE -- Research Company Deletion Date
    dlrsn: str = None  # DLRSN -- Research Co Reason for Deletion
    dltisy: int = None  # DLTISY -- Long-Term Debt - Issuance
    dltry: int = None  # DLTRY -- Long-Term Debt - Reduction
    dlttq: int = None  # DLTTQ -- Long-Term Debt - Total
    doq: int = None  # DOQ -- Discontinued Operations
    doy: int = None  # DOY -- Discontinued Operations
    dpacreq: int = None  # DPACREQ -- Accumulated Depreciation of RE Property
    dpactq: int = None  # DPACTQ -- Depreciation, Depletion and Amortization (Accumulated)
    dpcy: int = None  # DPCY -- Depreciation and Amortization - Statement of Cash Flows
    dpq: int = None  # DPQ -- Depreciation and Amortization - Total
    dpretq: int = None  # DPRETQ -- Depr/Amort of Property
    dprety: int = None  # DPRETY -- Depr/Amort of Property
    dpy: int = None  # DPY -- Depreciation and Amortization - Total
    drcq: int = None  # DRCQ -- Deferred Revenue - Current
    drltq: int = None  # DRLTQ -- Deferred Revenue - Long-term
    dteaq: int = None  # DTEAQ -- Extinguishment of Debt After-tax
    dteay: int = None  # DTEAY -- Extinguishment of Debt After-tax
    dtedq: int = None  # DTEDQ -- Extinguishment of Debt Diluted EPS Effect
    dtedy: int = None  # DTEDY -- Extinguishment of Debt Diluted EPS Effect
    dteepsq: int = None  # DTEEPSQ -- Extinguishment of Debt Basic EPS Effect
    dteepsy: int = None  # DTEEPSY -- Extinguishment of Debt Basic EPS Effect
    dtepq: int = None  # DTEPQ -- Extinguishment of Debt Pretax
    dtepy: int = None  # DTEPY -- Extinguishment of Debt Pretax
    dvintfq: int = None  # DVINTFQ -- Dividends & Interest Receivable (Cash Flow)
    dvpq: int = None  # DVPQ -- Dividends - Preferred/Preference
    dvpspq: int = None  # DVPSPQ -- Dividends per Share - Pay Date - Quarter
    dvpsxq: int = None  # DVPSXQ -- Div per Share - Exdate - Quarter
    dvpy: int = None  # DVPY -- Dividends - Preferred/Preference
    dvy: int = None  # DVY -- Cash Dividends
    ein: str = None  # EIN -- Employer Identification Number
    epsf12: int = None  # EPSF12 -- Earnings Per Share (Diluted) - Excluding Extraordinary Items - 12 Months Mo
    epsfi12: int = None  # EPSFI12 -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfiq: int = None  # EPSFIQ -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfiy: int = None  # EPSFIY -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfxq: int = None  # EPSFXQ -- Earnings Per Share (Diluted) - Excluding Extraordinary items
    epsfxy: int = None  # EPSFXY -- Earnings Per Share (Diluted) - Excluding Extraordinary items
    epspi12: int = None  # EPSPI12 -- Earnings Per Share (Basic) - Including Extraordinary Items - 12 Months Movi
    epspiq: int = None  # EPSPIQ -- Earnings Per Share (Basic) - Including Extraordinary Items
    epspiy: int = None  # EPSPIY -- Earnings Per Share (Basic) - Including Extraordinary Items
    epspxq: int = None  # EPSPXQ -- Earnings Per Share (Basic) - Excluding Extraordinary Items
    epspxy: int = None  # EPSPXY -- Earnings Per Share (Basic) - Excluding Extraordinary Items
    epsx12: int = None  # EPSX12 -- Earnings Per Share (Basic) - Excluding Extraordinary Items - 12 Months Movi
    esopctq: int = None  # ESOPCTQ -- Common ESOP Obligation - Total
    esopnrq: int = None  # ESOPNRQ -- Preferred ESOP Obligation - Non-Redeemable
    esoprq: int = None  # ESOPRQ -- Preferred ESOP Obligation - Redeemable
    esoptq: int = None  # ESOPTQ -- Preferred ESOP Obligation - Total
    esubcy: int = None  # ESUBCY -- Equity in Net Loss/Earnings (C/F)
    esubq: int = None  # ESUBQ -- Equity in Earnings (I/S) - Unconsolidated Subsidiaries
    esuby: int = None  # ESUBY -- Equity in Earnings (I/S)- Unconsolidated Subsidiaries
    exchg: int = None  # Stock Exchange Code
    exrey: int = None  # EXREY -- Exchange Rate Effect
    fax: str = None  # FAX -- Fax Number
    fcaq: int = None  # FCAQ -- Foreign Exchange Income (Loss)
    fcay: int = None  # FCAY -- Foreign Exchange Income (Loss)
    fdateq: str = None  # FDATEQ -- Final Date
    ffoq: int = None  # FFOQ -- Funds From Operations (REIT)
    ffoy: int = None  # FFOY -- Funds From Operations (REIT)
    fiaoy: int = None  # FIAOY -- Financing Activities - Other
    fic: str = None  # Foreign Incorporation Code
    finacoq: int = None  # FINACOQ -- Finance Division Other Current Assets, Total
    finalq: str = None  # FINALQ -- Final Indicator Flag
    finaoq: int = None  # FINAOQ -- Finance Division Other Long-Term Assets, Total
    fincfy: int = None  # FINCFY -- Financing Activities - Net Cash Flow
    finchq: int = None  # FINCHQ -- Finance Division - Cash
    findlcq: int = None  # FINDLCQ -- Finance Division Long-Term Debt - Current
    findltq: int = None  # FINDLTQ -- Finance Division Debt - Long-Term
    finivstq: int = None  # FINIVSTQ -- Finance Division - Short-Term Investments
    finlcoq: int = None  # FINLCOQ -- Finance Division Other Current Liabilities, Total
    finltoq: int = None  # FINLTOQ -- Finance Division Other Long Term Liabilities, Total
    finnpq: int = None  # FINNPQ -- Finance Division Notes Payable
    finreccq: int = None  # FINRECCQ -- Finance Division - Current Receivables
    finrecltq: int = None  # FINRECLTQ -- Finance Division - Long-Term Receivables
    finrevq: int = None  # FINREVQ -- Finance Division Revenue
    finrevy: int = None  # FINREVY -- Finance Division Revenue
    finxintq: int = None  # FINXINTQ -- Finance Division Interest Expense
    finxinty: int = None  # FINXINTY -- Finance Division Interest Expense
    finxoprq: int = None  # FINXOPRQ -- Finance Division Operating Expense
    finxopry: int = None  # FINXOPRY -- Finance Division Operating Expense
    fopoxy: int = None  # FOPOXY -- Funds from Operations - Other excluding Option Tax Benefit
    fopoy: int = None  # FOPOY -- Funds from Operations - Other
    fopty: int = None  # FOPTY -- Funds From Operations - Total
    fqtr: int = None  # FQTR -- Fiscal Quarter
    fsrcoy: int = None  # FSRCOY -- Sources of Funds - Other
    fsrcty: int = None  # FSRCTY -- Sources of Funds - Total
    fuseoy: int = None  # FUSEOY -- Uses of Funds - Other
    fusety: int = None  # FUSETY -- Uses of Funds - Total
    fyearq: int = None  # FYEARQ -- Fiscal Year
    fyr: int = None  # Fiscal Year-End
    fyr: int = None  # FYR -- Fiscal Year-end Month
    fyr: int = None  # FYR -- Fiscal Year-end Month
    fyrc: int = None  # FYRC -- Current Fiscal Year End Month
    gdwlamq: int = None  # GDWLAMQ -- Amortization of Goodwill
    gdwlamy: int = None  # GDWLAMY -- Amortization of Goodwill
    gdwlia12: int = None  # GDWLIA12 -- Impairments of Goodwill AfterTax - 12mm
    gdwliaq: int = None  # GDWLIAQ -- Impairment of Goodwill After-tax
    gdwliay: int = None  # GDWLIAY -- Impairment of Goodwill After-tax
    gdwlid12: int = None  # GDWLID12 -- Impairments Diluted EPS - 12mm
    gdwlidq: int = None  # GDWLIDQ -- Impairment of Goodwill Diluted EPS Effect
    gdwlidy: int = None  # GDWLIDY -- Impairment of Goodwill Diluted EPS Effect
    gdwlieps12: int = None  # GDWLIEPS12 -- Impairment of Goodwill Basic EPS Effect 12MM
    gdwliepsq: int = None  # GDWLIEPSQ -- Impairment of Goodwill Basic EPS Effect
    gdwliepsy: int = None  # GDWLIEPSY -- Impairment of Goodwill Basic EPS Effect
    gdwlipq: int = None  # GDWLIPQ -- Impairment of Goodwill Pretax
    gdwlipy: int = None  # GDWLIPY -- Impairment of Goodwill Pretax
    gdwlq: int = None  # GDWLQ -- Goodwill (net)
    ggroup: str = None  # GGROUP -- GIC Groups
    gind: str = None  # GIND -- GIC Industries
    glaq: int = None  # GLAQ -- Gain/Loss After-Tax
    glay: int = None  # GLAY -- Gain/Loss After-Tax
    glcea12: int = None  # GLCEA12 -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax 12MM
    glceaq: int = None  # GLCEAQ -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax
    glceay: int = None  # GLCEAY -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax
    glced12: int = None  # GLCED12 -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS Effect 12MM
    glcedq: int = None  # GLCEDQ -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS
    glcedy: int = None  # GLCEDY -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS
    glceeps12: int = None  # GLCEEPS12 -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect 12MM
    glceepsq: int = None  # GLCEEPSQ -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect
    glceepsy: int = None  # GLCEEPSY -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect
    glcepq: int = None  # GLCEPQ -- Gain/Loss on Sale (Core Earnings Adjusted) Pretax
    glcepy: int = None  # GLCEPY -- Gain/Loss on Sale (Core Earnings Adjusted) Pretax
    gldq: int = None  # GLDQ -- Gain/Loss Diluted EPS Effect
    gldy: int = None  # GLDY -- Gain/Loss Diluted EPS Effect
    glepsq: int = None  # GLEPSQ -- Gain/Loss Basic EPS Effect
    glepsy: int = None  # GLEPSY -- Gain/Loss Basic EPS Effect
    glivq: int = None  # GLIVQ -- Gains/Losses on investments
    glivy: int = None  # GLIVY -- Gains/Losses on investments
    glpq: int = None  # GLPQ -- Gain/Loss Pretax
    glpy: int = None  # GLPY -- Gain/Loss Pretax
    gsector: str = None  # GSECTOR -- GIC Sectors
    gsubind: str = None  # GSUBIND -- GIC Sub-Industries
    hedgeglq: int = None  # HEDGEGLQ -- Gain/Loss on Ineffective Hedges
    hedgegly: int = None  # HEDGEGLY -- Gain/Loss on Ineffective Hedges
    ibadj12: int = None  # IBADJ12 -- Income Before Extra Items - Adj for Common Stock Equivalents - 12MM
    ibadjq: int = None  # IBADJQ -- Income Before Extraordinary Items - Adjusted for Common Stock Equivalents
    ibadjy: int = None  # IBADJY -- Income Before Extraordinary Items - Adjusted for Common Stock Equivalents
    ibcomq: int = None  # IBCOMQ -- Income Before Extraordinary Items - Available for Common
    ibcomy: int = None  # IBCOMY -- Income Before Extraordinary Items - Available for Common
    ibcy: int = None  # IBCY -- Income Before Extraordinary Items - Statement of Cash Flows
    ibmiiq: int = None  # IBMIIQ -- Income before Extraordinary Items and Noncontrolling Interests
    ibmiiy: int = None  # IBMIIY -- Income before Extraordinary Items and Noncontrolling Interests
    ibq: int = None  # IBQ -- Income Before Extraordinary Items
    iby: int = None  # IBY -- Income Before Extraordinary Items
    icaptq: int = None  # ICAPTQ -- Invested Capital - Total - Quarterly
    idbflag: str = None  # IDBFLAG -- International, Domestic, Both Indicator
    incorp: str = None  # INCORP -- Current State/Province of Incorporation Code
    intaccq: int = None  # INTACCQ -- Interest Accrued
    intanoq: int = None  # INTANOQ -- Other Intangibles
    intanq: int = None  # INTANQ -- Intangible Assets - Total
    intpny: int = None  # INTPNY -- Interest Paid - Net
    invchy: int = None  # INVCHY -- Inventory - Decrease (Increase)
    invfgq: int = None  # INVFGQ -- Inventory - Finished Goods
    invoq: int = None  # INVOQ -- Inventory - Other
    invrmq: int = None  # INVRMQ -- Inventory - Raw Materials
    invtq: int = None  # INVTQ -- Inventories - Total
    invwipq: int = None  # INVWIPQ -- Inventory - Work in Process
    ipodate: str = None  # IPODATE -- Company Initial Public Offering Date
    itccy: int = None  # ITCCY -- Investment Tax Credit - Net (Cash Flow)
    ivacoy: int = None  # IVACOY -- Investing Activities - Other
    ivaeqq: int = None  # IVAEQQ -- Investment and Advances - Equity
    ivaoq: int = None  # IVAOQ -- Investment and Advances - Other
    ivchy: int = None  # IVCHY -- Increase in Investments
    ivltq: int = None  # IVLTQ -- Total Long-term Investments
    ivncfy: int = None  # IVNCFY -- Investing Activities - Net Cash Flow
    ivstchy: int = None  # IVSTCHY -- Short-Term Investments - Change
    ivstq: int = None  # IVSTQ -- Short-Term Investments- Total
    lcoq: int = None  # LCOQ -- Current Liabilities - Other - Total
    lctq: int = None  # LCTQ -- Current Liabilities - Total
    lltq: int = None  # LLTQ -- Long-Term Liabilities (Total)
    lnoq: int = None  # LNOQ -- Liabilities Netting & Other Adjustments
    loc: str = None  # LOC -- Current ISO Country Code - Headquarters
    lol2q: int = None  # LOL2Q -- Liabilities Level2 (Observable)
    loq: int = None  # LOQ -- Liabilities - Other
    loxdrq: int = None  # LOXDRQ -- Liabilities - Other - Excluding Deferred Revenue
    lqpl1q: int = None  # LQPL1Q -- Liabilities Level1 (Quoted Prices)
    lseq: int = None  # LSEQ -- Liabilities and Stockholders Equity - Total
    ltmibq: int = None  # LTMIBQ -- Liabilities - Total and Noncontrolling Interest
    ltq: int = None  # LTQ -- Liabilities - Total
    lul3q: int = None  # LUL3Q -- Liabilities Level3 (Unobservable)
    mibnq: int = None  # MIBNQ -- Noncontrolling Interests - Nonredeemable - Balance Sheet
    mibq: int = None  # MIBQ -- Noncontrolling Interest - Redeemable - Balance Sheet
    mibtq: int = None  # MIBTQ -- Noncontrolling Interests - Total - Balance Sheet
    miiq: int = None  # MIIQ -- Noncontrolling Interest - Income Account
    miiy: int = None  # MIIY -- Noncontrolling Interest - Income Account
    mkvaltq: int = None  # MKVALTQ -- Market Value - Total
    msaq: int = None  # MSAQ -- Accum Other Comp Inc - Marketable Security Adjustments
    naics: str = None  # NAICS -- North American Industry Classification Code
    ncoq: int = None  # NCOQ -- Net Charge-Offs
    ncoy: int = None  # NCOY -- Net Charge-Offs
    niitq: int = None  # NIITQ -- Net Interest Income (Tax Equivalent)
    niity: int = None  # NIITY -- Net Interest Income (Tax Equivalent)
    nimq: int = None  # NIMQ -- Net Interest Margin
    nimy: int = None  # NIMY -- Net Interest Margin
    niq: int = None  # NIQ -- Net Income (Loss)
    niy: int = None  # NIY -- Net Income (Loss)
    nopiq: int = None  # NOPIQ -- Non-Operating Income (Expense) - Total
    nopiy: int = None  # NOPIY -- Non-Operating Income (Expense) - Total
    npatq: int = None  # NPATQ -- Nonperforming Assets - Total
    npq: int = None  # NPQ -- Notes Payable
    nrtxtdq: int = None  # NRTXTDQ -- Nonrecurring Income Taxes Diluted EPS Effect
    nrtxtdy: int = None  # NRTXTDY -- Nonrecurring Income Taxes Diluted EPS Effect
    nrtxtepsq: int = None  # NRTXTEPSQ -- Nonrecurring Income Taxes Basic EPS Effect
    nrtxtepsy: int = None  # NRTXTEPSY -- Nonrecurring Income Taxes Basic EPS Effect
    nrtxtq: int = None  # NRTXTQ -- Nonrecurring Income Taxes - After-tax
    nrtxty: int = None  # NRTXTY -- Nonrecurring Income Taxes - After-tax
    oancfy: int = None  # OANCFY -- Operating Activities - Net Cash Flow
    obkq: int = None  # OBKQ -- Order backlog
    oepf12: int = None  # OEPF12 -- Earnings Per Share - Diluted - from Operations - 12MM
    oeps12: int = None  # OEPS12 -- Earnings Per Share from Operations - 12 Months Moving
    oepsxq: int = None  # OEPSXQ -- Earnings Per Share - Diluted - from Operations
    oepsxy: int = None  # OEPSXY -- Earnings Per Share - Diluted - from Operations
    ogmq: str = None  # OGMQ -- OIL & GAS METHOD
    oiadpq: int = None  # OIADPQ -- Operating Income After Depreciation - Quarterly
    oiadpy: int = None  # OIADPY -- Operating Income After Depreciation - Year-to-Date
    oibdpq: int = None  # OIBDPQ -- Operating Income Before Depreciation - Quarterly
    oibdpy: int = None  # OIBDPY -- Operating Income Before Depreciation
    opepsq: int = None  # OPEPSQ -- Earnings Per Share from Operations
    opepsy: int = None  # OPEPSY -- Earnings Per Share from Operations
    optdrq: int = None  # OPTDRQ -- Dividend Rate - Assumption (%)
    optdry: int = None  # OPTDRY -- Dividend Rate - Assumption (%)
    optfvgrq: int = None  # OPTFVGRQ -- Options - Fair Value of Options Granted
    optfvgry: int = None  # OPTFVGRY -- Options - Fair Value of Options Granted
    optlifeq: int = None  # OPTLIFEQ -- Life of Options - Assumption (## yrs)
    optlifey: int = None  # OPTLIFEY -- Life of Options - Assumption (## yrs)
    optrfrq: int = None  # OPTRFRQ -- Risk Free Rate - Assumption (%)
    optrfry: int = None  # OPTRFRY -- Risk Free Rate - Assumption (%)
    optvolq: int = None  # OPTVOLQ -- Volatility - Assumption (%)
    optvoly: int = None  # OPTVOLY -- Volatility - Assumption (%)
    pdateq: str = None  # PDATEQ -- Preliminary Date
    pdvcy: int = None  # PDVCY -- Cash Dividends on Preferred/Preference Stock (Cash Flow)
    phone: str = None  # PHONE -- Phone Number
    piq: int = None  # PIQ -- Pretax Income
    piy: int = None  # PIY -- Pretax Income
    pllq: int = None  # PLLQ -- Provision for Loan/Asset Losses
    plly: int = None  # PLLY -- Provision for Loan/Asset Losses
    pnc12: int = None  # PNC12 -- Pension Core Adjustment - 12mm
    pncd12: int = None  # PNCD12 -- Core Pension Adjustment Diluted EPS Effect 12MM
    pncdq: int = None  # PNCDQ -- Core Pension Adjustment Diluted EPS Effect
    pncdy: int = None  # PNCDY -- Core Pension Adjustment Diluted EPS Effect
    pnceps12: int = None  # PNCEPS12 -- Core Pension Adjustment Basic EPS Effect 12MM
    pncepsq: int = None  # PNCEPSQ -- Core Pension Adjustment Basic EPS Effect
    pncepsy: int = None  # PNCEPSY -- Core Pension Adjustment Basic EPS Effect
    pnciapq: int = None  # PNCIAPQ -- Core Pension Interest Adjustment After-tax Preliminary
    pnciapy: int = None  # PNCIAPY -- Core Pension Interest Adjustment After-tax Preliminary
    pnciaq: int = None  # PNCIAQ -- Core Pension Interest Adjustment After-tax
    pnciay: int = None  # PNCIAY -- Core Pension Interest Adjustment After-tax
    pncidpq: int = None  # PNCIDPQ -- Core Pension Interest Adjustment Diluted EPS Effect Preliminary
    pncidpy: int = None  # PNCIDPY -- Core Pension Interest Adjustment Diluted EPS Effect Preliminary
    pncidq: int = None  # PNCIDQ -- Core Pension Interest Adjustment Diluted EPS Effect
    pncidy: int = None  # PNCIDY -- Core Pension Interest Adjustment Diluted EPS Effect
    pnciepspq: int = None  # PNCIEPSPQ -- Core Pension Interest Adjustment Basic EPS Effect Preliminary
    pnciepspy: int = None  # PNCIEPSPY -- Core Pension Interest Adjustment Basic EPS Effect Preliminary
    pnciepsq: int = None  # PNCIEPSQ -- Core Pension Interest Adjustment Basic EPS Effect
    pnciepsy: int = None  # PNCIEPSY -- Core Pension Interest Adjustment Basic EPS Effect
    pncippq: int = None  # PNCIPPQ -- Core Pension Interest Adjustment Pretax Preliminary
    pncippy: int = None  # PNCIPPY -- Core Pension Interest Adjustment Pretax Preliminary
    pncipq: int = None  # PNCIPQ -- Core Pension Interest Adjustment Pretax
    pncipy: int = None  # PNCIPY -- Core Pension Interest Adjustment Pretax
    pncpd12: int = None  # PNCPD12 -- Core Pension Adjustment 12MM Diluted EPS Effect Preliminary
    pncpdq: int = None  # PNCPDQ -- Core Pension Adjustment Diluted EPS Effect Preliminary
    pncpdy: int = None  # PNCPDY -- Core Pension Adjustment Diluted EPS Effect Preliminary
    pncpeps12: int = None  # PNCPEPS12 -- Core Pension Adjustment 12MM Basic EPS Effect Preliminary
    pncpepsq: int = None  # PNCPEPSQ -- Core Pension Adjustment Basic EPS Effect Preliminary
    pncpepsy: int = None  # PNCPEPSY -- Core Pension Adjustment Basic EPS Effect Preliminary
    pncpq: int = None  # PNCPQ -- Core Pension Adjustment Preliminary
    pncpy: int = None  # PNCPY -- Core Pension Adjustment Preliminary
    pncq: int = None  # PNCQ -- Core Pension Adjustment
    pncwiapq: int = None  # PNCWIAPQ -- Core Pension w/o Interest Adjustment After-tax Preliminary
    pncwiapy: int = None  # PNCWIAPY -- Core Pension w/o Interest Adjustment After-tax Preliminary
    pncwiaq: int = None  # PNCWIAQ -- Core Pension w/o Interest Adjustment After-tax
    pncwiay: int = None  # PNCWIAY -- Core Pension w/o Interest Adjustment After-tax
    pncwidpq: int = None  # PNCWIDPQ -- Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary
    pncwidpy: int = None  # PNCWIDPY -- Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary
    pncwidq: int = None  # PNCWIDQ -- Core Pension w/o Interest Adjustment Diluted EPS Effect
    pncwidy: int = None  # PNCWIDY -- Core Pension w/o Interest Adjustment Diluted EPS Effect
    pncwiepq: int = None  # PNCWIEPQ -- Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary
    pncwiepsq: int = None  # PNCWIEPSQ -- Core Pension w/o Interest Adjustment Basic EPS Effect
    pncwiepsy: int = None  # PNCWIEPSY -- Core Pension w/o Interest Adjustment Basic EPS Effect
    pncwiepy: int = None  # PNCWIEPY -- Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary
    pncwippq: int = None  # PNCWIPPQ -- Core Pension w/o Interest Adjustment Pretax Preliminary
    pncwippy: int = None  # PNCWIPPY -- Core Pension w/o Interest Adjustment Pretax Preliminary
    pncwipq: int = None  # PNCWIPQ -- Core Pension w/o Interest Adjustment Pretax
    pncwipy: int = None  # PNCWIPY -- Core Pension w/o Interest Adjustment Pretax
    pncy: int = None  # PNCY -- Core Pension Adjustment
    pnrshoq: int = None  # PNRSHOQ -- Nonred Pfd Shares Outs (000) - Quarterly
    ppegtq: int = None  # PPEGTQ -- Property, Plant and Equipment - Total (Gross) - Quarterly
    ppentq: int = None  # PPENTQ -- Property Plant and Equipment - Total (Net)
    prcaq: int = None  # PRCAQ -- Core Post Retirement Adjustment
    prcay: int = None  # PRCAY -- Core Post Retirement Adjustment
    prccq: int = None  # PRCCQ -- Price Close - Quarter
    prcd12: int = None  # PRCD12 -- Core Post Retirement Adjustment Diluted EPS Effect 12MM
    prcdq: int = None  # PRCDQ -- Core Post Retirement Adjustment Diluted EPS Effect
    prcdy: int = None  # PRCDY -- Core Post Retirement Adjustment Diluted EPS Effect
    prce12: int = None  # PRCE12 -- Core Post Retirement Adjustment 12MM
    prceps12: int = None  # PRCEPS12 -- Core Post Retirement Adjustment Basic EPS Effect 12MM
    prcepsq: int = None  # PRCEPSQ -- Core Post Retirement Adjustment Basic EPS Effect
    prcepsy: int = None  # PRCEPSY -- Core Post Retirement Adjustment Basic EPS Effect
    prchq: int = None  # PRCHQ -- Price High - Quarter
    prclq: int = None  # PRCLQ -- Price Low - Quarter
    prcpd12: int = None  # PRCPD12 -- Core Post Retirement Adjustment 12MM Diluted EPS Effect Preliminary
    prcpdq: int = None  # PRCPDQ -- Core Post Retirement Adjustment Diluted EPS Effect Preliminary
    prcpdy: int = None  # PRCPDY -- Core Post Retirement Adjustment Diluted EPS Effect Preliminary
    prcpeps12: int = None  # PRCPEPS12 -- Core Post Retirement Adjustment 12MM Basic EPS Effect Preliminary
    prcpepsq: int = None  # PRCPEPSQ -- Core Post Retirement Adjustment Basic EPS Effect Preliminary
    prcpepsy: int = None  # PRCPEPSY -- Core Post Retirement Adjustment Basic EPS Effect Preliminary
    prcpq: int = None  # PRCPQ -- Core Post Retirement Adjustment Preliminary
    prcpy: int = None  # PRCPY -- Core Post Retirement Adjustment Preliminary
    prcraq: int = None  # PRCRAQ -- Repurchase Price - Average per share Quarter
    prican: str = None  # PRICAN -- Current Primary Issue Tag - Canada
    prirow: str = None  # PRIROW -- Primary Issue Tag - Rest of World
    priusa: str = None  # PRIUSA -- Current Primary Issue Tag - US
    prshoq: int = None  # PRSHOQ -- Redeem Pfd Shares Outs (000)
    prstkccy: int = None  # PRSTKCCY -- Purchase of Common Stock (Cash Flow)
    prstkcy: int = None  # PRSTKCY -- Purchase of Common and Preferred Stock
    prstkpcy: int = None  # PRSTKPCY -- Purchase of Preferred/Preference Stock (Cash Flow)
    pstknq: int = None  # PSTKNQ -- Preferred/Preference Stock - Nonredeemable
    pstkq: int = None  # PSTKQ -- Preferred/Preference Stock (Capital) - Total
    pstkrq: int = None  # PSTKRQ -- Preferred/Preference Stock - Redeemable
    rcaq: int = None  # RCAQ -- Restructuring Cost After-tax
    rcay: int = None  # RCAY -- Restructuring Cost After-tax
    rcdq: int = None  # RCDQ -- Restructuring Cost Diluted EPS Effect
    rcdy: int = None  # RCDY -- Restructuring Cost Diluted EPS Effect
    rcepsq: int = None  # RCEPSQ -- Restructuring Cost Basic EPS Effect
    rcepsy: int = None  # RCEPSY -- Restructuring Cost Basic EPS Effect
    rcpq: int = None  # RCPQ -- Restructuring Cost Pretax
    rcpy: int = None  # RCPY -- Restructuring Cost Pretax
    rdipaq: int = None  # RDIPAQ -- In Process R&D Expense After-tax
    rdipay: int = None  # RDIPAY -- In Process R&D Expense After-tax
    rdipdq: int = None  # RDIPDQ -- In Process R&D Expense Diluted EPS Effect
    rdipdy: int = None  # RDIPDY -- In Process R&D Expense Diluted EPS Effect
    rdipepsq: int = None  # RDIPEPSQ -- In Process R&D Expense Basic EPS Effect
    rdipepsy: int = None  # RDIPEPSY -- In Process R&D Expense Basic EPS Effect
    rdipq: int = None  # RDIPQ -- In Process R&D
    rdipy: int = None  # RDIPY -- In Process R&D
    rdq: str = None  # RDQ -- Report Date of Quarterly Earnings
    recchy: int = None  # RECCHY -- Accounts Receivable - Decrease (Increase)
    recdq: int = None  # RECDQ -- Receivables - Estimated Doubtful
    rectaq: int = None  # RECTAQ -- Accum Other Comp Inc - Cumulative Translation Adjustments
    rectoq: int = None  # RECTOQ -- Receivables - Current Other incl Tax Refunds
    rectq: int = None  # RECTQ -- Receivables - Total
    rectrq: int = None  # RECTRQ -- Receivables - Trade
    recubq: int = None  # RECUBQ -- Unbilled Receivables - Quarterly
    req: int = None  # REQ -- Retained Earnings
    retq: int = None  # RETQ -- Total RE Property
    reunaq: int = None  # REUNAQ -- Unadjusted Retained Earnings
    revtq: int = None  # REVTQ -- Revenue - Total
    revty: int = None  # REVTY -- Revenue - Total
    rllq: int = None  # RLLQ -- Reserve for Loan/Asset Losses
    rp: str = None  # RP -- Reporting Periodicity
    rra12: int = None  # RRA12 -- Reversal - Restructruring/Acquisition Aftertax 12MM
    rraq: int = None  # RRAQ -- Reversal - Restructruring/Acquisition Aftertax
    rray: int = None  # RRAY -- Reversal - Restructruring/Acquisition Aftertax
    rrd12: int = None  # RRD12 -- Reversal - Restructuring/Acq Diluted EPS Effect 12MM
    rrdq: int = None  # RRDQ -- Reversal - Restructuring/Acq Diluted EPS Effect
    rrdy: int = None  # RRDY -- Reversal - Restructuring/Acq Diluted EPS Effect
    rreps12: int = None  # RREPS12 -- Reversal - Restructuring/Acq Basic EPS Effect 12MM
    rrepsq: int = None  # RREPSQ -- Reversal - Restructuring/Acq Basic EPS Effect
    rrepsy: int = None  # RREPSY -- Reversal - Restructuring/Acq Basic EPS Effect
    rrpq: int = None  # RRPQ -- Reversal - Restructruring/Acquisition Pretax
    rrpy: int = None  # RRPY -- Reversal - Restructruring/Acquisition Pretax
    rstcheltq: int = None  # RSTCHELTQ -- Long-Term Restricted Cash & Investments
    rstcheq: int = None  # RSTCHEQ -- Restricted Cash & Investments - Current
    saleq: int = None  # SALEQ -- Sales/Turnover (Net)
    saley: int = None  # SALEY -- Sales/Turnover (Net)
    scfq: int = None  # SCFQ -- Cash Flow Model
    scstkcy: int = None  # SCSTKCY -- Sale of Common Stock (Cash Flow)
    seqoq: int = None  # SEQOQ -- Other Stockholders- Equity Adjustments
    seqq: int = None  # SEQQ -- Stockholders Equity > Parent > Index Fundamental > Quarterly
    seta12: int = None  # SETA12 -- Settlement (Litigation/Insurance) AfterTax - 12mm
    setaq: int = None  # SETAQ -- Settlement (Litigation/Insurance) After-tax
    setay: int = None  # SETAY -- Settlement (Litigation/Insurance) After-tax
    setd12: int = None  # SETD12 -- Settlement (Litigation/Insurance) Diluted EPS Effect 12MM
    setdq: int = None  # SETDQ -- Settlement (Litigation/Insurance) Diluted EPS Effect
    setdy: int = None  # SETDY -- Settlement (Litigation/Insurance) Diluted EPS Effect
    seteps12: int = None  # SETEPS12 -- Settlement (Litigation/Insurance) Basic EPS Effect 12MM
    setepsq: int = None  # SETEPSQ -- Settlement (Litigation/Insurance) Basic EPS Effect
    setepsy: int = None  # SETEPSY -- Settlement (Litigation/Insurance) Basic EPS Effect
    setpq: int = None  # SETPQ -- Settlement (Litigation/Insurance) Pretax
    setpy: int = None  # SETPY -- Settlement (Litigation/Insurance) Pretax
    sic: str = None  # SIC -- Standard Industry Classification Code
    sivy: int = None  # SIVY -- Sale of Investments
    spce12: int = None  # SPCE12 -- S&P Core Earnings 12MM
    spced12: int = None  # SPCED12 -- S&P Core Earnings EPS Diluted 12MM
    spcedpq: int = None  # SPCEDPQ -- S&P Core Earnings EPS Diluted - Preliminary
    spcedpy: int = None  # SPCEDPY -- S&P Core Earnings EPS Diluted - Preliminary
    spcedq: int = None  # SPCEDQ -- S&P Core Earnings EPS Diluted
    spcedy: int = None  # SPCEDY -- S&P Core Earnings EPS Diluted
    spceeps12: int = None  # SPCEEPS12 -- S&P Core Earnings EPS Basic 12MM
    spceepsp12: int = None  # SPCEEPSP12 -- S&P Core 12MM EPS - Basic - Preliminary
    spceepspq: int = None  # SPCEEPSPQ -- S&P Core Earnings EPS Basic - Preliminary
    spceepspy: int = None  # SPCEEPSPY -- S&P Core Earnings EPS Basic - Preliminary
    spceepsq: int = None  # SPCEEPSQ -- S&P Core Earnings EPS Basic
    spceepsy: int = None  # SPCEEPSY -- S&P Core Earnings EPS Basic
    spcep12: int = None  # SPCEP12 -- S&P Core Earnings 12MM - Preliminary
    spcepd12: int = None  # SPCEPD12 -- S&P Core Earnings 12MM EPS Diluted - Preliminary
    spcepq: int = None  # SPCEPQ -- S&P Core Earnings - Preliminary
    spcepy: int = None  # SPCEPY -- S&P Core Earnings - Preliminary
    spceq: int = None  # SPCEQ -- S&P Core Earnings
    spcey: int = None  # SPCEY -- S&P Core Earnings
    spcindcd: int = None  # SPCINDCD -- S&P Industry Sector Code
    spcseccd: int = None  # SPCSECCD -- S&P Economic Sector Code
    spcsrc: str = None  # SPCSRC -- S&P Quality Ranking - Current
    spidq: int = None  # SPIDQ -- Other Special Items Diluted EPS Effect
    spidy: int = None  # SPIDY -- Other Special Items Diluted EPS Effect
    spiepsq: int = None  # SPIEPSQ -- Other Special Items Basic EPS Effect
    spiepsy: int = None  # SPIEPSY -- Other Special Items Basic EPS Effect
    spioaq: int = None  # SPIOAQ -- Other Special Items After-tax
    spioay: int = None  # SPIOAY -- Other Special Items After-tax
    spiopq: int = None  # SPIOPQ -- Other Special Items Pretax
    spiopy: int = None  # SPIOPY -- Other Special Items Pretax
    spiq: int = None  # SPIQ -- Special Items
    spiy: int = None  # SPIY -- Special Items
    sppey: int = None  # SPPEY -- Sale of Property
    sppivy: int = None  # SPPIVY -- Sale of PP&E and Investments - (Gain) Loss
    spstkcy: int = None  # SPSTKCY -- Sale of Preferred/Preference Stock (Cash Flow)
    srcq: int = None  # SRCQ -- Source Code
    sretq: int = None  # SRETQ -- Gain/Loss on Sale of Property
    srety: int = None  # SRETY -- Gain/Loss on Sale of Property
    sstky: int = None  # SSTKY -- Sale of Common and Preferred Stock
    staltq: str = None  # STALTQ -- Status Alert
    state: str = None  # STATE -- State/Province
    stkcoq: int = None  # STKCOQ -- Stock Compensation Expense
    stkcoy: int = None  # STKCOY -- Stock Compensation Expense
    stkcpaq: int = None  # STKCPAQ -- After-tax stock compensation
    stkcpay: int = None  # STKCPAY -- After-tax stock compensation
    stko: int = None  # STKO -- Stock Ownership Code
    tdcy: int = None  # TDCY -- Deferred Income Taxes - Net (Cash Flow)
    teqq: int = None  # TEQQ -- Stockholders Equity - Total
    tfvaq: int = None  # TFVAQ -- Total Fair Value Assets
    tfvceq: int = None  # TFVCEQ -- Total Fair Value Changes including Earnings
    tfvcey: int = None  # TFVCEY -- Total Fair Value Changes including Earnings
    tfvlq: int = None  # TFVLQ -- Total Fair Value Liabilities
    tic: str = None  # Ticker Symbol
    tieq: int = None  # TIEQ -- Interest Expense - Total (Financial Services)
    tiey: int = None  # TIEY -- Interest Expense - Total (Financial Services)
    tiiq: int = None  # TIIQ -- Interest Income - Total (Financial Services)
    tiiy: int = None  # TIIY -- Interest Income - Total (Financial Services)
    tsafcy: int = None  # TSAFCY -- Total Srcs of Funds (FOF)
    tstknq: int = None  # TSTKNQ -- Treasury Stock - Number of Common Shares
    tstkq: int = None  # TSTKQ -- Treasury Stock - Total (All Capital)
    txachy: int = None  # TXACHY -- Income Taxes - Accrued - Increase (Decrease)
    txbcofy: int = None  # TXBCOFY -- Excess Tax Benefit of Stock Options - Cash Flow Financing
    txbcoy: int = None  # TXBCOY -- Excess Tax Benefit of Stock Options - Cash Flow Operating
    txdbaq: int = None  # TXDBAQ -- Deferred Tax Asset - Long Term
    txdbcaq: int = None  # TXDBCAQ -- Current Deferred Tax Asset
    txdbclq: int = None  # TXDBCLQ -- Current Deferred Tax Liability
    txdbq: int = None  # TXDBQ -- Deferred Taxes - Balance Sheet
    txdcy: int = None  # TXDCY -- Deferred Taxes (Statement of Cash Flows)
    txdiq: int = None  # TXDIQ -- Income Taxes - Deferred
    txditcq: int = None  # TXDITCQ -- Deferred Taxes and Investment Tax Credit
    txdiy: int = None  # TXDIY -- Income Taxes - Deferred
    txpdy: int = None  # TXPDY -- Income Taxes Paid
    txpq: int = None  # TXPQ -- Income Taxes Payable
    txtq: int = None  # TXTQ -- Income Taxes - Total
    txty: int = None  # TXTY -- Income Taxes - Total
    txwq: int = None  # TXWQ -- Excise Taxes
    txwy: int = None  # TXWY -- Excise Taxes
    uacoq: int = None  # UACOQ -- Current Assets - Other - Utility
    uaolochy: int = None  # UAOLOCHY -- Other Assets and Liabilities - Net Change (Statement of Cash Flows)
    uaoq: int = None  # UAOQ -- Other Assets - Utility
    uaptq: int = None  # UAPTQ -- Accounts Payable - Utility
    ucapsq: int = None  # UCAPSQ -- Paid In Capital - Other - Utility
    ucconsq: int = None  # UCCONSQ -- Contributions In Aid Of Construction
    uceqq: int = None  # UCEQQ -- Common Equity - Total - Utility
    uddq: int = None  # UDDQ -- Debt (Debentures) - Utility
    udfccy: int = None  # UDFCCY -- Deferred Fuel - Increase (Decrease) (Statement of Cash Flows)
    udmbq: int = None  # UDMBQ -- Debt (Mortgage Bonds)
    udoltq: int = None  # UDOLTQ -- Debt (Other Long-Term)
    udpcoq: int = None  # UDPCOQ -- Debt (Pollution Control Obligations)
    udvpq: int = None  # UDVPQ -- Preferred Dividend Requirements
    udvpy: int = None  # UDVPY -- Preferred Dividend Requirements - Utility
    ufretsdy: int = None  # UFRETSDY -- Tot Funds Ret ofSec&STD (FOF)
    ugiq: int = None  # UGIQ -- Gross Income (Income Before Interest Charges)
    ugiy: int = None  # UGIY -- Gross Income (Income Before Interest Charges) - Utility
    uinvq: int = None  # UINVQ -- Inventories
    ulcoq: int = None  # ULCOQ -- Current Liabilities - Other
    uniamiq: int = None  # UNIAMIQ -- Net Income before Extraordinary Items After Noncontrolling Interest
    uniamiy: int = None  # UNIAMIY -- Net Income before Extraordinary Items After Noncontrolling Interest - Utili
    unopincq: int = None  # UNOPINCQ -- Nonoperating Income (Net) - Other
    unopincy: int = None  # UNOPINCY -- Nonoperating Income (Net) - Other - Utility
    unwccy: int = None  # UNWCCY -- Inc(Dec)Working Cap (FOF)
    uoisy: int = None  # UOISY -- Other Internal Sources - Net (Cash Flow)
    uopiq: int = None  # UOPIQ -- Operating Income - Total - Utility
    updq: int = None  # UPDQ -- Update Code
    updvpq: int = None  # UPDVPQ -- Preference Dividend Requirements - Utility
    updvpy: int = None  # UPDVPY -- Preference Dividend Requirements - Utility
    upmcstkq: int = None  # UPMCSTKQ -- Premium On Common Stock - Utility
    upmpfq: int = None  # UPMPFQ -- Premium On Preferred Stock - Utility
    upmpfsq: int = None  # UPMPFSQ -- Premium On Preference Stock - Utility
    upmsubpq: int = None  # UPMSUBPQ -- Premium On Subsidiary Preferred Stock - Utility
    upstkcq: int = None  # UPSTKCQ -- Preference Stock At Carrying Value - Utility
    upstkq: int = None  # UPSTKQ -- Preferred Stock At Carrying Value - Utility
    uptacy: int = None  # UPTACY -- Utility Plant - Gross Additions (Cash Flow)
    urectq: int = None  # URECTQ -- Receivables (Net) - Utility
    uspiq: int = None  # USPIQ -- Special Items - Utility
    uspiy: int = None  # USPIY -- Special Items - Utility
    ustdncy: int = None  # USTDNCY -- Net Decr in ST Debt (FOF)
    usubdvpq: int = None  # USUBDVPQ -- Subsidiary Preferred Dividends - Utility
    usubdvpy: int = None  # USUBDVPY -- Subsidiary Preferred Dividends - Utility
    usubpcvq: int = None  # USUBPCVQ -- Subsidiary Preferred Stock At Carrying Value - Utility
    utemq: int = None  # UTEMQ -- Maintenance Expense - Total
    utfdocy: int = None  # UTFDOCY -- Total Funds From Ops (FOF)
    utfoscy: int = None  # UTFOSCY -- Tot Funds Frm Outside Sources (FOF)
    utmey: int = None  # UTMEY -- Maintenance Expense - Total
    uwkcapcy: int = None  # UWKCAPCY -- Dec(Inc) in Working Capital (FOF)
    wcapchy: int = None  # WCAPCHY -- Working Capital Changes - Total
    wcapcy: int = None  # WCAPCY -- Working Capital Change - Other - Increase/(Decrease)
    wcapq: int = None  # WCAPQ -- Working Capital (Balance Sheet)
    wdaq: int = None  # WDAQ -- Writedowns After-tax
    wday: int = None  # WDAY -- Writedowns After-tax
    wddq: int = None  # WDDQ -- Writedowns Diluted EPS Effect
    wddy: int = None  # WDDY -- Writedowns Diluted EPS Effect
    wdepsq: int = None  # WDEPSQ -- Writedowns Basic EPS Effect
    wdepsy: int = None  # WDEPSY -- Writedowns Basic EPS Effect
    wdpq: int = None  # WDPQ -- Writedowns Pretax
    wdpy: int = None  # WDPY -- Writedowns Pretax
    weburl: str = None  # WEBURL -- Web URL
    xaccq: int = None  # XACCQ -- Accrued Expenses
    xidocy: int = None  # XIDOCY -- Extraordinary Items and Discontinued Operations (Statement of Cash Flows)
    xidoq: int = None  # XIDOQ -- Extraordinary Items and Discontinued Operations
    xidoy: int = None  # XIDOY -- Extraordinary Items and Discontinued Operations
    xintq: int = None  # XINTQ -- Interest and Related Expense- Total
    xinty: int = None  # XINTY -- Interest and Related Expense- Total
    xiq: int = None  # XIQ -- Extraordinary Items
    xiy: int = None  # XIY -- Extraordinary Items
    xoprq: int = None  # XOPRQ -- Operating Expense- Total
    xopry: int = None  # XOPRY -- Operating Expense- Total
    xopt12: int = None  # XOPT12 -- Implied Option Expense - 12mm
    xoptd12: int = None  # XOPTD12 -- Implied Option EPS Diluted 12MM
    xoptd12p: int = None  # XOPTD12P -- Implied Option 12MM EPS Diluted Preliminary
    xoptdq: int = None  # XOPTDQ -- Implied Option EPS Diluted
    xoptdqp: int = None  # XOPTDQP -- Implied Option EPS Diluted Preliminary
    xoptdqpy: int = None  # XOPTDQPY -- Implied Option EPS Diluted Preliminary
    xoptdy: int = None  # XOPTDY -- Implied Option EPS Diluted
    xopteps12: int = None  # XOPTEPS12 -- Implied Option EPS Basic 12MM
    xoptepsp12: int = None  # XOPTEPSP12 -- Implied Option 12MM EPS Basic Preliminary
    xoptepsq: int = None  # XOPTEPSQ -- Implied Option EPS Basic
    xoptepsqp: int = None  # XOPTEPSQP -- Implied Option EPS Basic Preliminary
    xoptepsqpy: int = None  # XOPTEPSQPY -- Implied Option EPS Basic Preliminary
    xoptepsy: int = None  # XOPTEPSY -- Implied Option EPS Basic
    xoptq: int = None  # XOPTQ -- Implied Option Expense
    xoptqp: int = None  # XOPTQP -- Implied Option Expense Preliminary
    xoptqpy: int = None  # XOPTQPY -- Implied Option Expense Preliminary
    xopty: int = None  # XOPTY -- Implied Option Expense
    xrdq: int = None  # XRDQ -- Research and Development Expense
    xrdy: int = None  # XRDY -- Research and Development Expense
    xsgaq: int = None  # XSGAQ -- Selling, General and Administrative Expenses
    xsgay: int = None  # XSGAY -- Selling, General and Administrative Expenses

    @staticmethod
    def from_tic(tic):
        return super(Fdmt, Fdmt).from_attr(Fdmt, 'tic', tic, exact=True)

    @staticmethod
    def from_gvkey(gvkey):
        return super(Fdmt, Fdmt).from_attr(Fdmt, 'gvkey', gvkey, exact=True)