#!/usr/bin/env python3

import attr
from wrdscli.lib.base import WRDSEntity

@attr.s(auto_attribs=True)
class Fdmt(WRDSEntity):
    schema = 'comp'
    table = 'fundq'
    gvkey: str  # A Unique Global Company Key
    datadate: str  # Data Date
    popsrc: str  # Population Source
    iid: str  # Unique Issue ID
    indfmt: str  # Industry format
    datafmt: str  # Data Format
    consol: str  # Level of Consolidation
    costat: str  # Active/Inactive Status Marker
    curcdq: str = ''  # ISO Currency Code
    acchgq: int = -1  # ACCHGQ -- Accounting Changes - Cumulative Effect
    acchgy: int = -1  # ACCHGY -- Accounting Changes - Cumulative Effect
    acctchgq: str = ''  # ACCTCHGQ -- Adoption of Accounting Changes
    acctstdq: str = ''  # ACCTSTDQ -- Accounting Standard
    acomincq: int = -1  # ACOMINCQ -- Accumulated Other Comprehensive Income (Loss)
    acoq: int = -1  # ACOQ -- Current Assets - Other - Total
    actq: int = -1  # ACTQ -- Current Assets - Total
    add1: str = ''  # ADD1 -- Address Line 1
    add2: str = ''  # ADD2 -- Address Line 2
    add3: str = ''  # ADD3 -- Address Line 3
    add4: str = ''  # ADD4 -- Address Line 4
    addzip: str = ''  # ADDZIP -- Postal Code
    adjex: int = -1  # ADJEX -- Cumulative Adjustment Factor by Ex-Date
    adrrq: int = -1  # ADRRQ -- ADR Ratio
    afudccy: int = -1  # AFUDCCY -- Allowance for Funds Used During Construction (Cash Flow)
    afudciy: int = -1  # AFUDCIY -- Allowance for Funds Used During Construction (Investing) (Cash Flow)
    ajexq: int = -1  # AJEXQ -- Adjustment Factor (Company) - Cumulative by Ex-Date
    ajpq: int = -1  # AJPQ -- Adjustment Factor (Company) - Cumulative byPay-Date
    altoq: int = -1  # ALTOQ -- Other Long-term Assets
    amcy: int = -1  # AMCY -- Amortization (Cash Flow)
    ancq: int = -1  # ANCQ -- Non-Current Assets - Total
    anoq: int = -1  # ANOQ -- Assets Netting & Other Adjustments
    aociderglq: int = -1  # AOCIDERGLQ -- Accum Other Comp Inc - Derivatives Unrealized Gain/Loss
    aociotherq: int = -1  # AOCIOTHERQ -- Accum Other Comp Inc - Other Adjustments
    aocipenq: int = -1  # AOCIPENQ -- Accum Other Comp Inc - Min Pension Liab Adj
    aocisecglq: int = -1  # AOCISECGLQ -- Accum Other Comp Inc - Unreal G/L Ret Int in Sec Assets
    aol2q: int = -1  # AOL2Q -- Assets Level2 (Observable)
    aolochy: int = -1  # AOLOCHY -- Assets and Liabilities - Other (Net Change)
    aoq: int = -1  # AOQ -- Assets - Other - Total
    apalchy: int = -1  # APALCHY -- Accounts Payable and Accrued Liabilities - Increase (Decrease)
    apdedateq: str = ''  # APDEDATEQ -- Actual Period End date
    apq: int = -1  # APQ -- Account Payable/Creditors - Trade
    aqaq: int = -1  # AQAQ -- Acquisition/Merger After-Tax
    aqay: int = -1  # AQAY -- Acquisition/Merger After-Tax
    aqcy: int = -1  # AQCY -- Acquisitions
    aqdq: int = -1  # AQDQ -- Acquisition/Merger Diluted EPS Effect
    aqdy: int = -1  # AQDY -- Acquisition/Merger Diluted EPS Effect
    aqepsq: int = -1  # AQEPSQ -- Acquisition/Merger Basic EPS Effect
    aqepsy: int = -1  # AQEPSY -- Acquisition/Merger Basic EPS Effect
    aqpl1q: int = -1  # AQPL1Q -- Assets Level1 (Quoted Prices)
    aqpq: int = -1  # AQPQ -- Acquisition/Merger Pretax
    aqpy: int = -1  # AQPY -- Acquisition/Merger Pretax
    arcedq: int = -1  # ARCEDQ -- As Reported Core - Diluted EPS Effect
    arcedy: int = -1  # ARCEDY -- As Reported Core - Diluted EPS Effect
    arceepsq: int = -1  # ARCEEPSQ -- As Reported Core - Basic EPS Effect
    arceepsy: int = -1  # ARCEEPSY -- As Reported Core - Basic EPS Effect
    arceq: int = -1  # ARCEQ -- As Reported Core - After-tax
    arcey: int = -1  # ARCEY -- As Reported Core - After-tax
    atq: int = -1  # ATQ -- Assets - Total
    aul3q: int = -1  # AUL3Q -- Assets Level3 (Unobservable)
    billexceq: int = -1  # BILLEXCEQ -- Billings in Excess of Cost & Earnings
    bsprq: str = ''  # BSPRQ -- Balance Sheet Presentation
    busdesc: str = ''  # BUSDESC -- S&P Business Description
    capr1q: int = -1  # CAPR1Q -- Risk-Adjusted Capital Ratio - Tier 1
    capr2q: int = -1  # CAPR2Q -- Risk-Adjusted Capital Ratio - Tier 2
    capr3q: int = -1  # CAPR3Q -- Risk-Adjusted Capital Ratio - Combined
    capsftq: int = -1  # CAPSFTQ -- Capitalized Software
    capsq: int = -1  # CAPSQ -- Capital Surplus/Share Premium Reserve
    capxy: int = -1  # CAPXY -- Capital Expenditures
    cdvcy: int = -1  # CDVCY -- Cash Dividends on Common Stock (Cash Flow)
    ceiexbillq: int = -1  # CEIEXBILLQ -- Cost & Earnings in Excess of Billings
    ceqq: int = -1  # CEQQ -- Common/Ordinary Equity - Total
    chechy: int = -1  # CHECHY -- Cash and Cash Equivalents - Increase (Decrease)
    cheq: int = -1  # CHEQ -- Cash and Short-Term Investments
    chq: int = -1  # CHQ -- Cash
    cibegniq: int = -1  # CIBEGNIQ -- Comp Inc - Beginning Net Income
    cibegniy: int = -1  # CIBEGNIY -- Comp Inc - Beginning Net Income
    cicurrq: int = -1  # CICURRQ -- Comp Inc - Currency Trans Adj
    cicurry: int = -1  # CICURRY -- Comp Inc - Currency Trans Adj
    ciderglq: int = -1  # CIDERGLQ -- Comp Inc - Derivative Gains/Losses
    cidergly: int = -1  # CIDERGLY -- Comp Inc - Derivative Gains/Losses
    cik: str = ''  # CIK Number
    cimiiq: int = -1  # CIMIIQ -- Comprehensive Income - Noncontrolling Interest
    cimiiy: int = -1  # CIMIIY -- Comprehensive Income - Noncontrolling Interest
    ciotherq: int = -1  # CIOTHERQ -- Comp Inc - Other Adj
    ciothery: int = -1  # CIOTHERY -- Comp Inc - Other Adj
    cipenq: int = -1  # CIPENQ -- Comp Inc - Minimum Pension Adj
    cipeny: int = -1  # CIPENY -- Comp Inc - Minimum Pension Adj
    ciq: int = -1  # CIQ -- Comprehensive Income - Total
    cisecglq: int = -1  # CISECGLQ -- Comp Inc - Securities Gains/Losses
    cisecgly: int = -1  # CISECGLY -- Comp Inc - Securities Gains/Losses
    citotalq: int = -1  # CITOTALQ -- Comprehensive Income - Parent
    citotaly: int = -1  # CITOTALY -- Comprehensive Income - Parent
    city: str = ''  # CITY -- City
    ciy: int = -1  # CIY -- Comprehensive Income - Total
    cogsq: int = -1  # COGSQ -- Cost of Goods Sold
    cogsy: int = -1  # COGSY -- Cost of Goods Sold
    compstq: str = ''  # COMPSTQ -- Comparability Status
    conm: str = ''  # Company Name
    conml: str = ''  # CONML -- Company Legal Name
    county: str = ''  # COUNTY -- County Code
    csh12q: int = -1  # CSH12Q -- Common Shares Used to Calculate Earnings Per Share - 12 Months Moving
    cshfd12: int = -1  # CSHFD12 -- Common Shares Used to Calc Earnings Per Share - Fully Diluted - 12 Months M
    cshfdq: int = -1  # CSHFDQ -- Com Shares for Diluted EPS
    cshfdy: int = -1  # CSHFDY -- Com Shares for Diluted EPS
    cshiq: int = -1  # CSHIQ -- Common Shares Issued
    cshopq: int = -1  # CSHOPQ -- Total Shares Repurchased - Quarter
    cshoq: int = -1  # CSHOQ -- Common Shares Outstanding
    cshprq: int = -1  # CSHPRQ -- Common Shares Used to Calculate Earnings Per Share - Basic
    cshpry: int = -1  # CSHPRY -- Common Shares Used to Calculate Earnings Per Share - Basic
    cshtrq: int = -1  # CSHTRQ -- Common Shares Traded - Quarter
    cstkcvq: int = -1  # CSTKCVQ -- Carrying Value
    cstkeq: int = -1  # CSTKEQ -- Common Stock Equivalents - Dollar Savings
    cstkey: int = -1  # CSTKEY -- Common Stock Equivalents - Dollar Savings
    cstkq: int = -1  # CSTKQ -- Common/Ordinary Stock (Capital)
    curncdq: str = ''  # CURNCDQ -- Native Currency Code
    currtrq: int = -1  # CURRTRQ -- Currency Translation Rate
    curuscnq: int = -1  # CURUSCNQ -- US Canadian Translation Rate - Interim
    cusip: str = ''  # CUSIP
    datacqtr: str = ''  # DATACQTR -- Calendar Data Year and Quarter
    datafqtr: str = ''  # DATAFQTR -- Fiscal Data Year and Quarter
    dcomq: int = -1  # DCOMQ -- Deferred Compensation
    dd1q: int = -1  # DD1Q -- Long-Term Debt Due in One Year
    depcy: int = -1  # DEPCY -- Depreciation and Depletion (Cash Flow)
    deracq: int = -1  # DERACQ -- Derivative Assets - Current
    deraltq: int = -1  # DERALTQ -- Derivative Assets Long-Term
    derhedglq: int = -1  # DERHEDGLQ -- Gains/Losses on Derivatives and Hedging
    derhedgly: int = -1  # DERHEDGLY -- Gains/Losses on Derivatives and Hedging
    derlcq: int = -1  # DERLCQ -- Derivative Liabilities- Current
    derlltq: int = -1  # DERLLTQ -- Derivative Liabilities Long-Term
    diladq: int = -1  # DILADQ -- Dilution Adjustment
    dilady: int = -1  # DILADY -- Dilution Adjustment
    dilavq: int = -1  # DILAVQ -- Dilution Available - Excluding Extraordinary Items
    dilavy: int = -1  # DILAVY -- Dilution Available - Excluding Extraordinary Items
    dlcchy: int = -1  # DLCCHY -- Changes in Current Debt
    dlcq: int = -1  # DLCQ -- Debt in Current Liabilities
    dldte: str = ''  # DLDTE -- Research Company Deletion Date
    dlrsn: str = ''  # DLRSN -- Research Co Reason for Deletion
    dltisy: int = -1  # DLTISY -- Long-Term Debt - Issuance
    dltry: int = -1  # DLTRY -- Long-Term Debt - Reduction
    dlttq: int = -1  # DLTTQ -- Long-Term Debt - Total
    doq: int = -1  # DOQ -- Discontinued Operations
    doy: int = -1  # DOY -- Discontinued Operations
    dpacreq: int = -1  # DPACREQ -- Accumulated Depreciation of RE Property
    dpactq: int = -1  # DPACTQ -- Depreciation, Depletion and Amortization (Accumulated)
    dpcy: int = -1  # DPCY -- Depreciation and Amortization - Statement of Cash Flows
    dpq: int = -1  # DPQ -- Depreciation and Amortization - Total
    dpretq: int = -1  # DPRETQ -- Depr/Amort of Property
    dprety: int = -1  # DPRETY -- Depr/Amort of Property
    dpy: int = -1  # DPY -- Depreciation and Amortization - Total
    drcq: int = -1  # DRCQ -- Deferred Revenue - Current
    drltq: int = -1  # DRLTQ -- Deferred Revenue - Long-term
    dteaq: int = -1  # DTEAQ -- Extinguishment of Debt After-tax
    dteay: int = -1  # DTEAY -- Extinguishment of Debt After-tax
    dtedq: int = -1  # DTEDQ -- Extinguishment of Debt Diluted EPS Effect
    dtedy: int = -1  # DTEDY -- Extinguishment of Debt Diluted EPS Effect
    dteepsq: int = -1  # DTEEPSQ -- Extinguishment of Debt Basic EPS Effect
    dteepsy: int = -1  # DTEEPSY -- Extinguishment of Debt Basic EPS Effect
    dtepq: int = -1  # DTEPQ -- Extinguishment of Debt Pretax
    dtepy: int = -1  # DTEPY -- Extinguishment of Debt Pretax
    dvintfq: int = -1  # DVINTFQ -- Dividends & Interest Receivable (Cash Flow)
    dvpq: int = -1  # DVPQ -- Dividends - Preferred/Preference
    dvpspq: int = -1  # DVPSPQ -- Dividends per Share - Pay Date - Quarter
    dvpsxq: int = -1  # DVPSXQ -- Div per Share - Exdate - Quarter
    dvpy: int = -1  # DVPY -- Dividends - Preferred/Preference
    dvy: int = -1  # DVY -- Cash Dividends
    ein: str = ''  # EIN -- Employer Identification Number
    epsf12: int = -1  # EPSF12 -- Earnings Per Share (Diluted) - Excluding Extraordinary Items - 12 Months Mo
    epsfi12: int = -1  # EPSFI12 -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfiq: int = -1  # EPSFIQ -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfiy: int = -1  # EPSFIY -- Earnings Per Share (Diluted) - Including Extraordinary Items
    epsfxq: int = -1  # EPSFXQ -- Earnings Per Share (Diluted) - Excluding Extraordinary items
    epsfxy: int = -1  # EPSFXY -- Earnings Per Share (Diluted) - Excluding Extraordinary items
    epspi12: int = -1  # EPSPI12 -- Earnings Per Share (Basic) - Including Extraordinary Items - 12 Months Movi
    epspiq: int = -1  # EPSPIQ -- Earnings Per Share (Basic) - Including Extraordinary Items
    epspiy: int = -1  # EPSPIY -- Earnings Per Share (Basic) - Including Extraordinary Items
    epspxq: int = -1  # EPSPXQ -- Earnings Per Share (Basic) - Excluding Extraordinary Items
    epspxy: int = -1  # EPSPXY -- Earnings Per Share (Basic) - Excluding Extraordinary Items
    epsx12: int = -1  # EPSX12 -- Earnings Per Share (Basic) - Excluding Extraordinary Items - 12 Months Movi
    esopctq: int = -1  # ESOPCTQ -- Common ESOP Obligation - Total
    esopnrq: int = -1  # ESOPNRQ -- Preferred ESOP Obligation - Non-Redeemable
    esoprq: int = -1  # ESOPRQ -- Preferred ESOP Obligation - Redeemable
    esoptq: int = -1  # ESOPTQ -- Preferred ESOP Obligation - Total
    esubcy: int = -1  # ESUBCY -- Equity in Net Loss/Earnings (C/F)
    esubq: int = -1  # ESUBQ -- Equity in Earnings (I/S) - Unconsolidated Subsidiaries
    esuby: int = -1  # ESUBY -- Equity in Earnings (I/S)- Unconsolidated Subsidiaries
    exchg: int = -1  # Stock Exchange Code
    exrey: int = -1  # EXREY -- Exchange Rate Effect
    fax: str = ''  # FAX -- Fax Number
    fcaq: int = -1  # FCAQ -- Foreign Exchange Income (Loss)
    fcay: int = -1  # FCAY -- Foreign Exchange Income (Loss)
    fdateq: str = ''  # FDATEQ -- Final Date
    ffoq: int = -1  # FFOQ -- Funds From Operations (REIT)
    ffoy: int = -1  # FFOY -- Funds From Operations (REIT)
    fiaoy: int = -1  # FIAOY -- Financing Activities - Other
    fic: str = ''  # Foreign Incorporation Code
    finacoq: int = -1  # FINACOQ -- Finance Division Other Current Assets, Total
    finalq: str = ''  # FINALQ -- Final Indicator Flag
    finaoq: int = -1  # FINAOQ -- Finance Division Other Long-Term Assets, Total
    fincfy: int = -1  # FINCFY -- Financing Activities - Net Cash Flow
    finchq: int = -1  # FINCHQ -- Finance Division - Cash
    findlcq: int = -1  # FINDLCQ -- Finance Division Long-Term Debt - Current
    findltq: int = -1  # FINDLTQ -- Finance Division Debt - Long-Term
    finivstq: int = -1  # FINIVSTQ -- Finance Division - Short-Term Investments
    finlcoq: int = -1  # FINLCOQ -- Finance Division Other Current Liabilities, Total
    finltoq: int = -1  # FINLTOQ -- Finance Division Other Long Term Liabilities, Total
    finnpq: int = -1  # FINNPQ -- Finance Division Notes Payable
    finreccq: int = -1  # FINRECCQ -- Finance Division - Current Receivables
    finrecltq: int = -1  # FINRECLTQ -- Finance Division - Long-Term Receivables
    finrevq: int = -1  # FINREVQ -- Finance Division Revenue
    finrevy: int = -1  # FINREVY -- Finance Division Revenue
    finxintq: int = -1  # FINXINTQ -- Finance Division Interest Expense
    finxinty: int = -1  # FINXINTY -- Finance Division Interest Expense
    finxoprq: int = -1  # FINXOPRQ -- Finance Division Operating Expense
    finxopry: int = -1  # FINXOPRY -- Finance Division Operating Expense
    fopoxy: int = -1  # FOPOXY -- Funds from Operations - Other excluding Option Tax Benefit
    fopoy: int = -1  # FOPOY -- Funds from Operations - Other
    fopty: int = -1  # FOPTY -- Funds From Operations - Total
    fqtr: int = -1  # FQTR -- Fiscal Quarter
    fsrcoy: int = -1  # FSRCOY -- Sources of Funds - Other
    fsrcty: int = -1  # FSRCTY -- Sources of Funds - Total
    fuseoy: int = -1  # FUSEOY -- Uses of Funds - Other
    fusety: int = -1  # FUSETY -- Uses of Funds - Total
    fyearq: int = -1  # FYEARQ -- Fiscal Year
    fyr: int = -1  # Fiscal Year-End
    fyr: int = -1  # FYR -- Fiscal Year-end Month
    fyr: int = -1  # FYR -- Fiscal Year-end Month
    fyrc: int = -1  # FYRC -- Current Fiscal Year End Month
    gdwlamq: int = -1  # GDWLAMQ -- Amortization of Goodwill
    gdwlamy: int = -1  # GDWLAMY -- Amortization of Goodwill
    gdwlia12: int = -1  # GDWLIA12 -- Impairments of Goodwill AfterTax - 12mm
    gdwliaq: int = -1  # GDWLIAQ -- Impairment of Goodwill After-tax
    gdwliay: int = -1  # GDWLIAY -- Impairment of Goodwill After-tax
    gdwlid12: int = -1  # GDWLID12 -- Impairments Diluted EPS - 12mm
    gdwlidq: int = -1  # GDWLIDQ -- Impairment of Goodwill Diluted EPS Effect
    gdwlidy: int = -1  # GDWLIDY -- Impairment of Goodwill Diluted EPS Effect
    gdwlieps12: int = -1  # GDWLIEPS12 -- Impairment of Goodwill Basic EPS Effect 12MM
    gdwliepsq: int = -1  # GDWLIEPSQ -- Impairment of Goodwill Basic EPS Effect
    gdwliepsy: int = -1  # GDWLIEPSY -- Impairment of Goodwill Basic EPS Effect
    gdwlipq: int = -1  # GDWLIPQ -- Impairment of Goodwill Pretax
    gdwlipy: int = -1  # GDWLIPY -- Impairment of Goodwill Pretax
    gdwlq: int = -1  # GDWLQ -- Goodwill (net)
    ggroup: str = ''  # GGROUP -- GIC Groups
    gind: str = ''  # GIND -- GIC Industries
    glaq: int = -1  # GLAQ -- Gain/Loss After-Tax
    glay: int = -1  # GLAY -- Gain/Loss After-Tax
    glcea12: int = -1  # GLCEA12 -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax 12MM
    glceaq: int = -1  # GLCEAQ -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax
    glceay: int = -1  # GLCEAY -- Gain/Loss on Sale (Core Earnings Adjusted) After-tax
    glced12: int = -1  # GLCED12 -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS Effect 12MM
    glcedq: int = -1  # GLCEDQ -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS
    glcedy: int = -1  # GLCEDY -- Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS
    glceeps12: int = -1  # GLCEEPS12 -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect 12MM
    glceepsq: int = -1  # GLCEEPSQ -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect
    glceepsy: int = -1  # GLCEEPSY -- Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect
    glcepq: int = -1  # GLCEPQ -- Gain/Loss on Sale (Core Earnings Adjusted) Pretax
    glcepy: int = -1  # GLCEPY -- Gain/Loss on Sale (Core Earnings Adjusted) Pretax
    gldq: int = -1  # GLDQ -- Gain/Loss Diluted EPS Effect
    gldy: int = -1  # GLDY -- Gain/Loss Diluted EPS Effect
    glepsq: int = -1  # GLEPSQ -- Gain/Loss Basic EPS Effect
    glepsy: int = -1  # GLEPSY -- Gain/Loss Basic EPS Effect
    glivq: int = -1  # GLIVQ -- Gains/Losses on investments
    glivy: int = -1  # GLIVY -- Gains/Losses on investments
    glpq: int = -1  # GLPQ -- Gain/Loss Pretax
    glpy: int = -1  # GLPY -- Gain/Loss Pretax
    gsector: str = ''  # GSECTOR -- GIC Sectors
    gsubind: str = ''  # GSUBIND -- GIC Sub-Industries
    hedgeglq: int = -1  # HEDGEGLQ -- Gain/Loss on Ineffective Hedges
    hedgegly: int = -1  # HEDGEGLY -- Gain/Loss on Ineffective Hedges
    ibadj12: int = -1  # IBADJ12 -- Income Before Extra Items - Adj for Common Stock Equivalents - 12MM
    ibadjq: int = -1  # IBADJQ -- Income Before Extraordinary Items - Adjusted for Common Stock Equivalents
    ibadjy: int = -1  # IBADJY -- Income Before Extraordinary Items - Adjusted for Common Stock Equivalents
    ibcomq: int = -1  # IBCOMQ -- Income Before Extraordinary Items - Available for Common
    ibcomy: int = -1  # IBCOMY -- Income Before Extraordinary Items - Available for Common
    ibcy: int = -1  # IBCY -- Income Before Extraordinary Items - Statement of Cash Flows
    ibmiiq: int = -1  # IBMIIQ -- Income before Extraordinary Items and Noncontrolling Interests
    ibmiiy: int = -1  # IBMIIY -- Income before Extraordinary Items and Noncontrolling Interests
    ibq: int = -1  # IBQ -- Income Before Extraordinary Items
    iby: int = -1  # IBY -- Income Before Extraordinary Items
    icaptq: int = -1  # ICAPTQ -- Invested Capital - Total - Quarterly
    idbflag: str = ''  # IDBFLAG -- International, Domestic, Both Indicator
    incorp: str = ''  # INCORP -- Current State/Province of Incorporation Code
    intaccq: int = -1  # INTACCQ -- Interest Accrued
    intanoq: int = -1  # INTANOQ -- Other Intangibles
    intanq: int = -1  # INTANQ -- Intangible Assets - Total
    intpny: int = -1  # INTPNY -- Interest Paid - Net
    invchy: int = -1  # INVCHY -- Inventory - Decrease (Increase)
    invfgq: int = -1  # INVFGQ -- Inventory - Finished Goods
    invoq: int = -1  # INVOQ -- Inventory - Other
    invrmq: int = -1  # INVRMQ -- Inventory - Raw Materials
    invtq: int = -1  # INVTQ -- Inventories - Total
    invwipq: int = -1  # INVWIPQ -- Inventory - Work in Process
    ipodate: str = ''  # IPODATE -- Company Initial Public Offering Date
    itccy: int = -1  # ITCCY -- Investment Tax Credit - Net (Cash Flow)
    ivacoy: int = -1  # IVACOY -- Investing Activities - Other
    ivaeqq: int = -1  # IVAEQQ -- Investment and Advances - Equity
    ivaoq: int = -1  # IVAOQ -- Investment and Advances - Other
    ivchy: int = -1  # IVCHY -- Increase in Investments
    ivltq: int = -1  # IVLTQ -- Total Long-term Investments
    ivncfy: int = -1  # IVNCFY -- Investing Activities - Net Cash Flow
    ivstchy: int = -1  # IVSTCHY -- Short-Term Investments - Change
    ivstq: int = -1  # IVSTQ -- Short-Term Investments- Total
    lcoq: int = -1  # LCOQ -- Current Liabilities - Other - Total
    lctq: int = -1  # LCTQ -- Current Liabilities - Total
    lltq: int = -1  # LLTQ -- Long-Term Liabilities (Total)
    lnoq: int = -1  # LNOQ -- Liabilities Netting & Other Adjustments
    loc: str = ''  # LOC -- Current ISO Country Code - Headquarters
    lol2q: int = -1  # LOL2Q -- Liabilities Level2 (Observable)
    loq: int = -1  # LOQ -- Liabilities - Other
    loxdrq: int = -1  # LOXDRQ -- Liabilities - Other - Excluding Deferred Revenue
    lqpl1q: int = -1  # LQPL1Q -- Liabilities Level1 (Quoted Prices)
    lseq: int = -1  # LSEQ -- Liabilities and Stockholders Equity - Total
    ltmibq: int = -1  # LTMIBQ -- Liabilities - Total and Noncontrolling Interest
    ltq: int = -1  # LTQ -- Liabilities - Total
    lul3q: int = -1  # LUL3Q -- Liabilities Level3 (Unobservable)
    mibnq: int = -1  # MIBNQ -- Noncontrolling Interests - Nonredeemable - Balance Sheet
    mibq: int = -1  # MIBQ -- Noncontrolling Interest - Redeemable - Balance Sheet
    mibtq: int = -1  # MIBTQ -- Noncontrolling Interests - Total - Balance Sheet
    miiq: int = -1  # MIIQ -- Noncontrolling Interest - Income Account
    miiy: int = -1  # MIIY -- Noncontrolling Interest - Income Account
    mkvaltq: int = -1  # MKVALTQ -- Market Value - Total
    msaq: int = -1  # MSAQ -- Accum Other Comp Inc - Marketable Security Adjustments
    naics: str = ''  # NAICS -- North American Industry Classification Code
    ncoq: int = -1  # NCOQ -- Net Charge-Offs
    ncoy: int = -1  # NCOY -- Net Charge-Offs
    niitq: int = -1  # NIITQ -- Net Interest Income (Tax Equivalent)
    niity: int = -1  # NIITY -- Net Interest Income (Tax Equivalent)
    nimq: int = -1  # NIMQ -- Net Interest Margin
    nimy: int = -1  # NIMY -- Net Interest Margin
    niq: int = -1  # NIQ -- Net Income (Loss)
    niy: int = -1  # NIY -- Net Income (Loss)
    nopiq: int = -1  # NOPIQ -- Non-Operating Income (Expense) - Total
    nopiy: int = -1  # NOPIY -- Non-Operating Income (Expense) - Total
    npatq: int = -1  # NPATQ -- Nonperforming Assets - Total
    npq: int = -1  # NPQ -- Notes Payable
    nrtxtdq: int = -1  # NRTXTDQ -- Nonrecurring Income Taxes Diluted EPS Effect
    nrtxtdy: int = -1  # NRTXTDY -- Nonrecurring Income Taxes Diluted EPS Effect
    nrtxtepsq: int = -1  # NRTXTEPSQ -- Nonrecurring Income Taxes Basic EPS Effect
    nrtxtepsy: int = -1  # NRTXTEPSY -- Nonrecurring Income Taxes Basic EPS Effect
    nrtxtq: int = -1  # NRTXTQ -- Nonrecurring Income Taxes - After-tax
    nrtxty: int = -1  # NRTXTY -- Nonrecurring Income Taxes - After-tax
    oancfy: int = -1  # OANCFY -- Operating Activities - Net Cash Flow
    obkq: int = -1  # OBKQ -- Order backlog
    oepf12: int = -1  # OEPF12 -- Earnings Per Share - Diluted - from Operations - 12MM
    oeps12: int = -1  # OEPS12 -- Earnings Per Share from Operations - 12 Months Moving
    oepsxq: int = -1  # OEPSXQ -- Earnings Per Share - Diluted - from Operations
    oepsxy: int = -1  # OEPSXY -- Earnings Per Share - Diluted - from Operations
    ogmq: str = ''  # OGMQ -- OIL & GAS METHOD
    oiadpq: int = -1  # OIADPQ -- Operating Income After Depreciation - Quarterly
    oiadpy: int = -1  # OIADPY -- Operating Income After Depreciation - Year-to-Date
    oibdpq: int = -1  # OIBDPQ -- Operating Income Before Depreciation - Quarterly
    oibdpy: int = -1  # OIBDPY -- Operating Income Before Depreciation
    opepsq: int = -1  # OPEPSQ -- Earnings Per Share from Operations
    opepsy: int = -1  # OPEPSY -- Earnings Per Share from Operations
    optdrq: int = -1  # OPTDRQ -- Dividend Rate - Assumption (%)
    optdry: int = -1  # OPTDRY -- Dividend Rate - Assumption (%)
    optfvgrq: int = -1  # OPTFVGRQ -- Options - Fair Value of Options Granted
    optfvgry: int = -1  # OPTFVGRY -- Options - Fair Value of Options Granted
    optlifeq: int = -1  # OPTLIFEQ -- Life of Options - Assumption (## yrs)
    optlifey: int = -1  # OPTLIFEY -- Life of Options - Assumption (## yrs)
    optrfrq: int = -1  # OPTRFRQ -- Risk Free Rate - Assumption (%)
    optrfry: int = -1  # OPTRFRY -- Risk Free Rate - Assumption (%)
    optvolq: int = -1  # OPTVOLQ -- Volatility - Assumption (%)
    optvoly: int = -1  # OPTVOLY -- Volatility - Assumption (%)
    pdateq: str = ''  # PDATEQ -- Preliminary Date
    pdvcy: int = -1  # PDVCY -- Cash Dividends on Preferred/Preference Stock (Cash Flow)
    phone: str = ''  # PHONE -- Phone Number
    piq: int = -1  # PIQ -- Pretax Income
    piy: int = -1  # PIY -- Pretax Income
    pllq: int = -1  # PLLQ -- Provision for Loan/Asset Losses
    plly: int = -1  # PLLY -- Provision for Loan/Asset Losses
    pnc12: int = -1  # PNC12 -- Pension Core Adjustment - 12mm
    pncd12: int = -1  # PNCD12 -- Core Pension Adjustment Diluted EPS Effect 12MM
    pncdq: int = -1  # PNCDQ -- Core Pension Adjustment Diluted EPS Effect
    pncdy: int = -1  # PNCDY -- Core Pension Adjustment Diluted EPS Effect
    pnceps12: int = -1  # PNCEPS12 -- Core Pension Adjustment Basic EPS Effect 12MM
    pncepsq: int = -1  # PNCEPSQ -- Core Pension Adjustment Basic EPS Effect
    pncepsy: int = -1  # PNCEPSY -- Core Pension Adjustment Basic EPS Effect
    pnciapq: int = -1  # PNCIAPQ -- Core Pension Interest Adjustment After-tax Preliminary
    pnciapy: int = -1  # PNCIAPY -- Core Pension Interest Adjustment After-tax Preliminary
    pnciaq: int = -1  # PNCIAQ -- Core Pension Interest Adjustment After-tax
    pnciay: int = -1  # PNCIAY -- Core Pension Interest Adjustment After-tax
    pncidpq: int = -1  # PNCIDPQ -- Core Pension Interest Adjustment Diluted EPS Effect Preliminary
    pncidpy: int = -1  # PNCIDPY -- Core Pension Interest Adjustment Diluted EPS Effect Preliminary
    pncidq: int = -1  # PNCIDQ -- Core Pension Interest Adjustment Diluted EPS Effect
    pncidy: int = -1  # PNCIDY -- Core Pension Interest Adjustment Diluted EPS Effect
    pnciepspq: int = -1  # PNCIEPSPQ -- Core Pension Interest Adjustment Basic EPS Effect Preliminary
    pnciepspy: int = -1  # PNCIEPSPY -- Core Pension Interest Adjustment Basic EPS Effect Preliminary
    pnciepsq: int = -1  # PNCIEPSQ -- Core Pension Interest Adjustment Basic EPS Effect
    pnciepsy: int = -1  # PNCIEPSY -- Core Pension Interest Adjustment Basic EPS Effect
    pncippq: int = -1  # PNCIPPQ -- Core Pension Interest Adjustment Pretax Preliminary
    pncippy: int = -1  # PNCIPPY -- Core Pension Interest Adjustment Pretax Preliminary
    pncipq: int = -1  # PNCIPQ -- Core Pension Interest Adjustment Pretax
    pncipy: int = -1  # PNCIPY -- Core Pension Interest Adjustment Pretax
    pncpd12: int = -1  # PNCPD12 -- Core Pension Adjustment 12MM Diluted EPS Effect Preliminary
    pncpdq: int = -1  # PNCPDQ -- Core Pension Adjustment Diluted EPS Effect Preliminary
    pncpdy: int = -1  # PNCPDY -- Core Pension Adjustment Diluted EPS Effect Preliminary
    pncpeps12: int = -1  # PNCPEPS12 -- Core Pension Adjustment 12MM Basic EPS Effect Preliminary
    pncpepsq: int = -1  # PNCPEPSQ -- Core Pension Adjustment Basic EPS Effect Preliminary
    pncpepsy: int = -1  # PNCPEPSY -- Core Pension Adjustment Basic EPS Effect Preliminary
    pncpq: int = -1  # PNCPQ -- Core Pension Adjustment Preliminary
    pncpy: int = -1  # PNCPY -- Core Pension Adjustment Preliminary
    pncq: int = -1  # PNCQ -- Core Pension Adjustment
    pncwiapq: int = -1  # PNCWIAPQ -- Core Pension w/o Interest Adjustment After-tax Preliminary
    pncwiapy: int = -1  # PNCWIAPY -- Core Pension w/o Interest Adjustment After-tax Preliminary
    pncwiaq: int = -1  # PNCWIAQ -- Core Pension w/o Interest Adjustment After-tax
    pncwiay: int = -1  # PNCWIAY -- Core Pension w/o Interest Adjustment After-tax
    pncwidpq: int = -1  # PNCWIDPQ -- Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary
    pncwidpy: int = -1  # PNCWIDPY -- Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary
    pncwidq: int = -1  # PNCWIDQ -- Core Pension w/o Interest Adjustment Diluted EPS Effect
    pncwidy: int = -1  # PNCWIDY -- Core Pension w/o Interest Adjustment Diluted EPS Effect
    pncwiepq: int = -1  # PNCWIEPQ -- Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary
    pncwiepsq: int = -1  # PNCWIEPSQ -- Core Pension w/o Interest Adjustment Basic EPS Effect
    pncwiepsy: int = -1  # PNCWIEPSY -- Core Pension w/o Interest Adjustment Basic EPS Effect
    pncwiepy: int = -1  # PNCWIEPY -- Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary
    pncwippq: int = -1  # PNCWIPPQ -- Core Pension w/o Interest Adjustment Pretax Preliminary
    pncwippy: int = -1  # PNCWIPPY -- Core Pension w/o Interest Adjustment Pretax Preliminary
    pncwipq: int = -1  # PNCWIPQ -- Core Pension w/o Interest Adjustment Pretax
    pncwipy: int = -1  # PNCWIPY -- Core Pension w/o Interest Adjustment Pretax
    pncy: int = -1  # PNCY -- Core Pension Adjustment
    pnrshoq: int = -1  # PNRSHOQ -- Nonred Pfd Shares Outs (000) - Quarterly
    ppegtq: int = -1  # PPEGTQ -- Property, Plant and Equipment - Total (Gross) - Quarterly
    ppentq: int = -1  # PPENTQ -- Property Plant and Equipment - Total (Net)
    prcaq: int = -1  # PRCAQ -- Core Post Retirement Adjustment
    prcay: int = -1  # PRCAY -- Core Post Retirement Adjustment
    prccq: int = -1  # PRCCQ -- Price Close - Quarter
    prcd12: int = -1  # PRCD12 -- Core Post Retirement Adjustment Diluted EPS Effect 12MM
    prcdq: int = -1  # PRCDQ -- Core Post Retirement Adjustment Diluted EPS Effect
    prcdy: int = -1  # PRCDY -- Core Post Retirement Adjustment Diluted EPS Effect
    prce12: int = -1  # PRCE12 -- Core Post Retirement Adjustment 12MM
    prceps12: int = -1  # PRCEPS12 -- Core Post Retirement Adjustment Basic EPS Effect 12MM
    prcepsq: int = -1  # PRCEPSQ -- Core Post Retirement Adjustment Basic EPS Effect
    prcepsy: int = -1  # PRCEPSY -- Core Post Retirement Adjustment Basic EPS Effect
    prchq: int = -1  # PRCHQ -- Price High - Quarter
    prclq: int = -1  # PRCLQ -- Price Low - Quarter
    prcpd12: int = -1  # PRCPD12 -- Core Post Retirement Adjustment 12MM Diluted EPS Effect Preliminary
    prcpdq: int = -1  # PRCPDQ -- Core Post Retirement Adjustment Diluted EPS Effect Preliminary
    prcpdy: int = -1  # PRCPDY -- Core Post Retirement Adjustment Diluted EPS Effect Preliminary
    prcpeps12: int = -1  # PRCPEPS12 -- Core Post Retirement Adjustment 12MM Basic EPS Effect Preliminary
    prcpepsq: int = -1  # PRCPEPSQ -- Core Post Retirement Adjustment Basic EPS Effect Preliminary
    prcpepsy: int = -1  # PRCPEPSY -- Core Post Retirement Adjustment Basic EPS Effect Preliminary
    prcpq: int = -1  # PRCPQ -- Core Post Retirement Adjustment Preliminary
    prcpy: int = -1  # PRCPY -- Core Post Retirement Adjustment Preliminary
    prcraq: int = -1  # PRCRAQ -- Repurchase Price - Average per share Quarter
    prican: str = ''  # PRICAN -- Current Primary Issue Tag - Canada
    prirow: str = ''  # PRIROW -- Primary Issue Tag - Rest of World
    priusa: str = ''  # PRIUSA -- Current Primary Issue Tag - US
    prshoq: int = -1  # PRSHOQ -- Redeem Pfd Shares Outs (000)
    prstkccy: int = -1  # PRSTKCCY -- Purchase of Common Stock (Cash Flow)
    prstkcy: int = -1  # PRSTKCY -- Purchase of Common and Preferred Stock
    prstkpcy: int = -1  # PRSTKPCY -- Purchase of Preferred/Preference Stock (Cash Flow)
    pstknq: int = -1  # PSTKNQ -- Preferred/Preference Stock - Nonredeemable
    pstkq: int = -1  # PSTKQ -- Preferred/Preference Stock (Capital) - Total
    pstkrq: int = -1  # PSTKRQ -- Preferred/Preference Stock - Redeemable
    rcaq: int = -1  # RCAQ -- Restructuring Cost After-tax
    rcay: int = -1  # RCAY -- Restructuring Cost After-tax
    rcdq: int = -1  # RCDQ -- Restructuring Cost Diluted EPS Effect
    rcdy: int = -1  # RCDY -- Restructuring Cost Diluted EPS Effect
    rcepsq: int = -1  # RCEPSQ -- Restructuring Cost Basic EPS Effect
    rcepsy: int = -1  # RCEPSY -- Restructuring Cost Basic EPS Effect
    rcpq: int = -1  # RCPQ -- Restructuring Cost Pretax
    rcpy: int = -1  # RCPY -- Restructuring Cost Pretax
    rdipaq: int = -1  # RDIPAQ -- In Process R&D Expense After-tax
    rdipay: int = -1  # RDIPAY -- In Process R&D Expense After-tax
    rdipdq: int = -1  # RDIPDQ -- In Process R&D Expense Diluted EPS Effect
    rdipdy: int = -1  # RDIPDY -- In Process R&D Expense Diluted EPS Effect
    rdipepsq: int = -1  # RDIPEPSQ -- In Process R&D Expense Basic EPS Effect
    rdipepsy: int = -1  # RDIPEPSY -- In Process R&D Expense Basic EPS Effect
    rdipq: int = -1  # RDIPQ -- In Process R&D
    rdipy: int = -1  # RDIPY -- In Process R&D
    rdq: str = ''  # RDQ -- Report Date of Quarterly Earnings
    recchy: int = -1  # RECCHY -- Accounts Receivable - Decrease (Increase)
    recdq: int = -1  # RECDQ -- Receivables - Estimated Doubtful
    rectaq: int = -1  # RECTAQ -- Accum Other Comp Inc - Cumulative Translation Adjustments
    rectoq: int = -1  # RECTOQ -- Receivables - Current Other incl Tax Refunds
    rectq: int = -1  # RECTQ -- Receivables - Total
    rectrq: int = -1  # RECTRQ -- Receivables - Trade
    recubq: int = -1  # RECUBQ -- Unbilled Receivables - Quarterly
    req: int = -1  # REQ -- Retained Earnings
    retq: int = -1  # RETQ -- Total RE Property
    reunaq: int = -1  # REUNAQ -- Unadjusted Retained Earnings
    revtq: int = -1  # REVTQ -- Revenue - Total
    revty: int = -1  # REVTY -- Revenue - Total
    rllq: int = -1  # RLLQ -- Reserve for Loan/Asset Losses
    rp: str = ''  # RP -- Reporting Periodicity
    rra12: int = -1  # RRA12 -- Reversal - Restructruring/Acquisition Aftertax 12MM
    rraq: int = -1  # RRAQ -- Reversal - Restructruring/Acquisition Aftertax
    rray: int = -1  # RRAY -- Reversal - Restructruring/Acquisition Aftertax
    rrd12: int = -1  # RRD12 -- Reversal - Restructuring/Acq Diluted EPS Effect 12MM
    rrdq: int = -1  # RRDQ -- Reversal - Restructuring/Acq Diluted EPS Effect
    rrdy: int = -1  # RRDY -- Reversal - Restructuring/Acq Diluted EPS Effect
    rreps12: int = -1  # RREPS12 -- Reversal - Restructuring/Acq Basic EPS Effect 12MM
    rrepsq: int = -1  # RREPSQ -- Reversal - Restructuring/Acq Basic EPS Effect
    rrepsy: int = -1  # RREPSY -- Reversal - Restructuring/Acq Basic EPS Effect
    rrpq: int = -1  # RRPQ -- Reversal - Restructruring/Acquisition Pretax
    rrpy: int = -1  # RRPY -- Reversal - Restructruring/Acquisition Pretax
    rstcheltq: int = -1  # RSTCHELTQ -- Long-Term Restricted Cash & Investments
    rstcheq: int = -1  # RSTCHEQ -- Restricted Cash & Investments - Current
    saleq: int = -1  # SALEQ -- Sales/Turnover (Net)
    saley: int = -1  # SALEY -- Sales/Turnover (Net)
    scfq: int = -1  # SCFQ -- Cash Flow Model
    scstkcy: int = -1  # SCSTKCY -- Sale of Common Stock (Cash Flow)
    seqoq: int = -1  # SEQOQ -- Other Stockholders- Equity Adjustments
    seqq: int = -1  # SEQQ -- Stockholders Equity > Parent > Index Fundamental > Quarterly
    seta12: int = -1  # SETA12 -- Settlement (Litigation/Insurance) AfterTax - 12mm
    setaq: int = -1  # SETAQ -- Settlement (Litigation/Insurance) After-tax
    setay: int = -1  # SETAY -- Settlement (Litigation/Insurance) After-tax
    setd12: int = -1  # SETD12 -- Settlement (Litigation/Insurance) Diluted EPS Effect 12MM
    setdq: int = -1  # SETDQ -- Settlement (Litigation/Insurance) Diluted EPS Effect
    setdy: int = -1  # SETDY -- Settlement (Litigation/Insurance) Diluted EPS Effect
    seteps12: int = -1  # SETEPS12 -- Settlement (Litigation/Insurance) Basic EPS Effect 12MM
    setepsq: int = -1  # SETEPSQ -- Settlement (Litigation/Insurance) Basic EPS Effect
    setepsy: int = -1  # SETEPSY -- Settlement (Litigation/Insurance) Basic EPS Effect
    setpq: int = -1  # SETPQ -- Settlement (Litigation/Insurance) Pretax
    setpy: int = -1  # SETPY -- Settlement (Litigation/Insurance) Pretax
    sic: str = ''  # SIC -- Standard Industry Classification Code
    sivy: int = -1  # SIVY -- Sale of Investments
    spce12: int = -1  # SPCE12 -- S&P Core Earnings 12MM
    spced12: int = -1  # SPCED12 -- S&P Core Earnings EPS Diluted 12MM
    spcedpq: int = -1  # SPCEDPQ -- S&P Core Earnings EPS Diluted - Preliminary
    spcedpy: int = -1  # SPCEDPY -- S&P Core Earnings EPS Diluted - Preliminary
    spcedq: int = -1  # SPCEDQ -- S&P Core Earnings EPS Diluted
    spcedy: int = -1  # SPCEDY -- S&P Core Earnings EPS Diluted
    spceeps12: int = -1  # SPCEEPS12 -- S&P Core Earnings EPS Basic 12MM
    spceepsp12: int = -1  # SPCEEPSP12 -- S&P Core 12MM EPS - Basic - Preliminary
    spceepspq: int = -1  # SPCEEPSPQ -- S&P Core Earnings EPS Basic - Preliminary
    spceepspy: int = -1  # SPCEEPSPY -- S&P Core Earnings EPS Basic - Preliminary
    spceepsq: int = -1  # SPCEEPSQ -- S&P Core Earnings EPS Basic
    spceepsy: int = -1  # SPCEEPSY -- S&P Core Earnings EPS Basic
    spcep12: int = -1  # SPCEP12 -- S&P Core Earnings 12MM - Preliminary
    spcepd12: int = -1  # SPCEPD12 -- S&P Core Earnings 12MM EPS Diluted - Preliminary
    spcepq: int = -1  # SPCEPQ -- S&P Core Earnings - Preliminary
    spcepy: int = -1  # SPCEPY -- S&P Core Earnings - Preliminary
    spceq: int = -1  # SPCEQ -- S&P Core Earnings
    spcey: int = -1  # SPCEY -- S&P Core Earnings
    spcindcd: int = -1  # SPCINDCD -- S&P Industry Sector Code
    spcseccd: int = -1  # SPCSECCD -- S&P Economic Sector Code
    spcsrc: str = ''  # SPCSRC -- S&P Quality Ranking - Current
    spidq: int = -1  # SPIDQ -- Other Special Items Diluted EPS Effect
    spidy: int = -1  # SPIDY -- Other Special Items Diluted EPS Effect
    spiepsq: int = -1  # SPIEPSQ -- Other Special Items Basic EPS Effect
    spiepsy: int = -1  # SPIEPSY -- Other Special Items Basic EPS Effect
    spioaq: int = -1  # SPIOAQ -- Other Special Items After-tax
    spioay: int = -1  # SPIOAY -- Other Special Items After-tax
    spiopq: int = -1  # SPIOPQ -- Other Special Items Pretax
    spiopy: int = -1  # SPIOPY -- Other Special Items Pretax
    spiq: int = -1  # SPIQ -- Special Items
    spiy: int = -1  # SPIY -- Special Items
    sppey: int = -1  # SPPEY -- Sale of Property
    sppivy: int = -1  # SPPIVY -- Sale of PP&E and Investments - (Gain) Loss
    spstkcy: int = -1  # SPSTKCY -- Sale of Preferred/Preference Stock (Cash Flow)
    srcq: int = -1  # SRCQ -- Source Code
    sretq: int = -1  # SRETQ -- Gain/Loss on Sale of Property
    srety: int = -1  # SRETY -- Gain/Loss on Sale of Property
    sstky: int = -1  # SSTKY -- Sale of Common and Preferred Stock
    staltq: str = ''  # STALTQ -- Status Alert
    state: str = ''  # STATE -- State/Province
    stkcoq: int = -1  # STKCOQ -- Stock Compensation Expense
    stkcoy: int = -1  # STKCOY -- Stock Compensation Expense
    stkcpaq: int = -1  # STKCPAQ -- After-tax stock compensation
    stkcpay: int = -1  # STKCPAY -- After-tax stock compensation
    stko: int = -1  # STKO -- Stock Ownership Code
    tdcy: int = -1  # TDCY -- Deferred Income Taxes - Net (Cash Flow)
    teqq: int = -1  # TEQQ -- Stockholders Equity - Total
    tfvaq: int = -1  # TFVAQ -- Total Fair Value Assets
    tfvceq: int = -1  # TFVCEQ -- Total Fair Value Changes including Earnings
    tfvcey: int = -1  # TFVCEY -- Total Fair Value Changes including Earnings
    tfvlq: int = -1  # TFVLQ -- Total Fair Value Liabilities
    tic: str = ''  # Ticker Symbol
    tieq: int = -1  # TIEQ -- Interest Expense - Total (Financial Services)
    tiey: int = -1  # TIEY -- Interest Expense - Total (Financial Services)
    tiiq: int = -1  # TIIQ -- Interest Income - Total (Financial Services)
    tiiy: int = -1  # TIIY -- Interest Income - Total (Financial Services)
    tsafcy: int = -1  # TSAFCY -- Total Srcs of Funds (FOF)
    tstknq: int = -1  # TSTKNQ -- Treasury Stock - Number of Common Shares
    tstkq: int = -1  # TSTKQ -- Treasury Stock - Total (All Capital)
    txachy: int = -1  # TXACHY -- Income Taxes - Accrued - Increase (Decrease)
    txbcofy: int = -1  # TXBCOFY -- Excess Tax Benefit of Stock Options - Cash Flow Financing
    txbcoy: int = -1  # TXBCOY -- Excess Tax Benefit of Stock Options - Cash Flow Operating
    txdbaq: int = -1  # TXDBAQ -- Deferred Tax Asset - Long Term
    txdbcaq: int = -1  # TXDBCAQ -- Current Deferred Tax Asset
    txdbclq: int = -1  # TXDBCLQ -- Current Deferred Tax Liability
    txdbq: int = -1  # TXDBQ -- Deferred Taxes - Balance Sheet
    txdcy: int = -1  # TXDCY -- Deferred Taxes (Statement of Cash Flows)
    txdiq: int = -1  # TXDIQ -- Income Taxes - Deferred
    txditcq: int = -1  # TXDITCQ -- Deferred Taxes and Investment Tax Credit
    txdiy: int = -1  # TXDIY -- Income Taxes - Deferred
    txpdy: int = -1  # TXPDY -- Income Taxes Paid
    txpq: int = -1  # TXPQ -- Income Taxes Payable
    txtq: int = -1  # TXTQ -- Income Taxes - Total
    txty: int = -1  # TXTY -- Income Taxes - Total
    txwq: int = -1  # TXWQ -- Excise Taxes
    txwy: int = -1  # TXWY -- Excise Taxes
    uacoq: int = -1  # UACOQ -- Current Assets - Other - Utility
    uaolochy: int = -1  # UAOLOCHY -- Other Assets and Liabilities - Net Change (Statement of Cash Flows)
    uaoq: int = -1  # UAOQ -- Other Assets - Utility
    uaptq: int = -1  # UAPTQ -- Accounts Payable - Utility
    ucapsq: int = -1  # UCAPSQ -- Paid In Capital - Other - Utility
    ucconsq: int = -1  # UCCONSQ -- Contributions In Aid Of Construction
    uceqq: int = -1  # UCEQQ -- Common Equity - Total - Utility
    uddq: int = -1  # UDDQ -- Debt (Debentures) - Utility
    udfccy: int = -1  # UDFCCY -- Deferred Fuel - Increase (Decrease) (Statement of Cash Flows)
    udmbq: int = -1  # UDMBQ -- Debt (Mortgage Bonds)
    udoltq: int = -1  # UDOLTQ -- Debt (Other Long-Term)
    udpcoq: int = -1  # UDPCOQ -- Debt (Pollution Control Obligations)
    udvpq: int = -1  # UDVPQ -- Preferred Dividend Requirements
    udvpy: int = -1  # UDVPY -- Preferred Dividend Requirements - Utility
    ufretsdy: int = -1  # UFRETSDY -- Tot Funds Ret ofSec&STD (FOF)
    ugiq: int = -1  # UGIQ -- Gross Income (Income Before Interest Charges)
    ugiy: int = -1  # UGIY -- Gross Income (Income Before Interest Charges) - Utility
    uinvq: int = -1  # UINVQ -- Inventories
    ulcoq: int = -1  # ULCOQ -- Current Liabilities - Other
    uniamiq: int = -1  # UNIAMIQ -- Net Income before Extraordinary Items After Noncontrolling Interest
    uniamiy: int = -1  # UNIAMIY -- Net Income before Extraordinary Items After Noncontrolling Interest - Utili
    unopincq: int = -1  # UNOPINCQ -- Nonoperating Income (Net) - Other
    unopincy: int = -1  # UNOPINCY -- Nonoperating Income (Net) - Other - Utility
    unwccy: int = -1  # UNWCCY -- Inc(Dec)Working Cap (FOF)
    uoisy: int = -1  # UOISY -- Other Internal Sources - Net (Cash Flow)
    uopiq: int = -1  # UOPIQ -- Operating Income - Total - Utility
    updq: int = -1  # UPDQ -- Update Code
    updvpq: int = -1  # UPDVPQ -- Preference Dividend Requirements - Utility
    updvpy: int = -1  # UPDVPY -- Preference Dividend Requirements - Utility
    upmcstkq: int = -1  # UPMCSTKQ -- Premium On Common Stock - Utility
    upmpfq: int = -1  # UPMPFQ -- Premium On Preferred Stock - Utility
    upmpfsq: int = -1  # UPMPFSQ -- Premium On Preference Stock - Utility
    upmsubpq: int = -1  # UPMSUBPQ -- Premium On Subsidiary Preferred Stock - Utility
    upstkcq: int = -1  # UPSTKCQ -- Preference Stock At Carrying Value - Utility
    upstkq: int = -1  # UPSTKQ -- Preferred Stock At Carrying Value - Utility
    uptacy: int = -1  # UPTACY -- Utility Plant - Gross Additions (Cash Flow)
    urectq: int = -1  # URECTQ -- Receivables (Net) - Utility
    uspiq: int = -1  # USPIQ -- Special Items - Utility
    uspiy: int = -1  # USPIY -- Special Items - Utility
    ustdncy: int = -1  # USTDNCY -- Net Decr in ST Debt (FOF)
    usubdvpq: int = -1  # USUBDVPQ -- Subsidiary Preferred Dividends - Utility
    usubdvpy: int = -1  # USUBDVPY -- Subsidiary Preferred Dividends - Utility
    usubpcvq: int = -1  # USUBPCVQ -- Subsidiary Preferred Stock At Carrying Value - Utility
    utemq: int = -1  # UTEMQ -- Maintenance Expense - Total
    utfdocy: int = -1  # UTFDOCY -- Total Funds From Ops (FOF)
    utfoscy: int = -1  # UTFOSCY -- Tot Funds Frm Outside Sources (FOF)
    utmey: int = -1  # UTMEY -- Maintenance Expense - Total
    uwkcapcy: int = -1  # UWKCAPCY -- Dec(Inc) in Working Capital (FOF)
    wcapchy: int = -1  # WCAPCHY -- Working Capital Changes - Total
    wcapcy: int = -1  # WCAPCY -- Working Capital Change - Other - Increase/(Decrease)
    wcapq: int = -1  # WCAPQ -- Working Capital (Balance Sheet)
    wdaq: int = -1  # WDAQ -- Writedowns After-tax
    wday: int = -1  # WDAY -- Writedowns After-tax
    wddq: int = -1  # WDDQ -- Writedowns Diluted EPS Effect
    wddy: int = -1  # WDDY -- Writedowns Diluted EPS Effect
    wdepsq: int = -1  # WDEPSQ -- Writedowns Basic EPS Effect
    wdepsy: int = -1  # WDEPSY -- Writedowns Basic EPS Effect
    wdpq: int = -1  # WDPQ -- Writedowns Pretax
    wdpy: int = -1  # WDPY -- Writedowns Pretax
    weburl: str = ''  # WEBURL -- Web URL
    xaccq: int = -1  # XACCQ -- Accrued Expenses
    xidocy: int = -1  # XIDOCY -- Extraordinary Items and Discontinued Operations (Statement of Cash Flows)
    xidoq: int = -1  # XIDOQ -- Extraordinary Items and Discontinued Operations
    xidoy: int = -1  # XIDOY -- Extraordinary Items and Discontinued Operations
    xintq: int = -1  # XINTQ -- Interest and Related Expense- Total
    xinty: int = -1  # XINTY -- Interest and Related Expense- Total
    xiq: int = -1  # XIQ -- Extraordinary Items
    xiy: int = -1  # XIY -- Extraordinary Items
    xoprq: int = -1  # XOPRQ -- Operating Expense- Total
    xopry: int = -1  # XOPRY -- Operating Expense- Total
    xopt12: int = -1  # XOPT12 -- Implied Option Expense - 12mm
    xoptd12: int = -1  # XOPTD12 -- Implied Option EPS Diluted 12MM
    xoptd12p: int = -1  # XOPTD12P -- Implied Option 12MM EPS Diluted Preliminary
    xoptdq: int = -1  # XOPTDQ -- Implied Option EPS Diluted
    xoptdqp: int = -1  # XOPTDQP -- Implied Option EPS Diluted Preliminary
    xoptdqpy: int = -1  # XOPTDQPY -- Implied Option EPS Diluted Preliminary
    xoptdy: int = -1  # XOPTDY -- Implied Option EPS Diluted
    xopteps12: int = -1  # XOPTEPS12 -- Implied Option EPS Basic 12MM
    xoptepsp12: int = -1  # XOPTEPSP12 -- Implied Option 12MM EPS Basic Preliminary
    xoptepsq: int = -1  # XOPTEPSQ -- Implied Option EPS Basic
    xoptepsqp: int = -1  # XOPTEPSQP -- Implied Option EPS Basic Preliminary
    xoptepsqpy: int = -1  # XOPTEPSQPY -- Implied Option EPS Basic Preliminary
    xoptepsy: int = -1  # XOPTEPSY -- Implied Option EPS Basic
    xoptq: int = -1  # XOPTQ -- Implied Option Expense
    xoptqp: int = -1  # XOPTQP -- Implied Option Expense Preliminary
    xoptqpy: int = -1  # XOPTQPY -- Implied Option Expense Preliminary
    xopty: int = -1  # XOPTY -- Implied Option Expense
    xrdq: int = -1  # XRDQ -- Research and Development Expense
    xrdy: int = -1  # XRDY -- Research and Development Expense
    xsgaq: int = -1  # XSGAQ -- Selling, General and Administrative Expenses
    xsgay: int = -1  # XSGAY -- Selling, General and Administrative Expenses

    @staticmethod
    def from_tic(tic):
        return super(Fdmt, Fdmt).from_attr(Fdmt, 'tic', tic, exact=True)

    @staticmethod
    def from_gvkey(gvkey):
        return super(Fdmt, Fdmt).from_attr(Fdmt, 'gvkey', gvkey, exact=True)